var m=void 0,q=null,u=q;function v(a,b){if(b===q||typeof b=="undefined")b=a,a=0;a<0?b+=Math.abs(a):b-=a;return Math.floor(Math.random()*b)+a}function aa(a){var b=0,e;for(e in a)b++;return b}function ba(a,b){if(typeof b!="number")return!1;return b<a?1:b>a?-1:0}function ca(a,b){var e=a.c==w?"None":"Natives";if(b!=q)e=b.m;return e}function da(a){var b="Asteroid Belt";a==ea?b="Dead":a==fa?b="Arid":a==ga&&(b="Terrestrial");return b}
function ha(a){var b="";switch(a){case x:b="Factory";break;case y:b="Colony";break;case z:b="Farm";break;case A:b="Mine";break;case B:b="Space Platform"}return b}function ia(a){var b="";switch(a){case E:b="Defender";break;case F:b="Scout";break;case G:b="Destroyer";break;case H:b="Cruiser";break;case I:b="Battleship"}return b}
function ja(a){var b=[],b=b.concat(ka(a,la(a)));if(a.c==ma)for(var e in a.j){var d=a.j[e];if(d.Ca&&d.p.length==0&&d.za!=q){var g=new J(d.za);if(a.d.t-g.u>a.Fa&&na(a)-g.D>=0&&oa(a)-g.G>=0){var h=a;d.p.push(g);pa(d,g.u,g.D,g.G,h)}}}var g=d=e=0,i;for(i in a.j)h=new qa,ra(a.j[i],h),e+=h.ib,d+=h.Xa,g+=h.Ra;a.d.da+=(e+g+d)/2;a.d.Ba();for(i in a.j)sa(a.j[i]);b=b.concat(ta(a));return b=b.concat(va(a))}
function wa(a){var b=[],e=[],d;for(d in a.jb)e.push(a.jb[d]);a.jb={};for(var g in e){d=e[g];var h=d.ca.R,i=h.k,f=L(i),j=L(d),l=new xa(h.q,i,a,d);if(f>j*4)l.kb=1;else if(j>f*4)l.kb=f==0?100:99;else{var k=0;j>f?(k=50+Math.round(Math.log(j/(f*1))/Math.log(Math.pow(4,2))*100),l.kb=k):(k=50+Math.round(Math.log(f/(j*1))/Math.log(Math.pow(4,2))*100),l.kb=100-k)}for(var f=d,j=i,k=q,n={},o={enemyFleetSpacePlatformDamagePending:0},p={},r={enemyFleetSpacePlatformDamagePending:0};L(f,!0)>0&&L(j,!0)>0;){var s=
ya(f),D=ya(j),K;for(K in s){var ua=s[K];za(Aa(ua),ua.c,!1,D,j.F,p,r)}f.F&&za(64-f.la,E,!0,D,j.F,n,r);for(K in D)ua=D[K],za(Aa(ua),ua.c,!1,s,f.F,n,o);j.F&&za(64-j.la,E,!0,s,f.F,n,o);for(K in n)s=n[K],s.Starship.qa+=s.Damage;n={};for(K in p)s=p[K],s.Starship.qa+=s.Damage;p={};Ba(f,o.enemyFleetSpacePlatformDamagePending);Ba(j,r.enemyFleetSpacePlatformDamagePending)}L(f,!0)>0?k=!0:L(j,!0)>0&&(k=!1);f=k;if(f===q||typeof f=="undefined")f=!1;if(f){i=h.q;f=Ca(h,a);if(i){f+=Math.floor(Math.pow(h.c+1,2));if(a.d.t<
f)f=i.d.t;l.Za=v(0,Math.floor(f+1));i.d.t-=l.Za;a.d.t+=l.Za}h.k=new Da;Ea(h.k,d,d.ca);i!=q&&Fa(h,i);if(a==u.H)f="Your fleet captured planet: "+h.m,i!=q&&(f="Your fleet captured planet: "+h.m+", owned by: "+i.m),h=new M(Ga,h,f),h.I=l,h.I.qb=Ha(d),b.push(h);else if(i==u.H)f=a.m+" captured your planet: "+h.m,h=new M(Ia,h,f),h.I=l,h.I.qb=Ha(d),b.push(h)}else if(f=h,j=a,j.va[f.b]=f,Fa(f,j),d.wb!=q&&d.wb(d),a==u.H)f="You lost a fleet attacking planet: "+h.m,h.q!=q&&(f="You lost a fleet attacking "+h.q.m+
" at planet: "+h.m),h=new M(Ja,h,f),h.I=l,h.I.qb=Ha(i),b.push(h);else if(h.q==u.H)f="You successfully defended against "+a.m+" attacking planet: "+h.m,h=new M(Ka,h,f),h.I=l,h.I.qb=Ha(i),b.push(h)}return b}
function ka(a,b){var e=[];a.Fa=0;var d={},g=[],h;for(h in a.j){var i=a.j[h];i.ea=La;i.d.O-=i.r.length;if(i.d.O<0){var f=Math.abs(i.d.O);d[i.b]=f;i.d.O=0;a.Fa+=f}else i.d.O>0&&g.push(i)}h=0;var i="",j=0,l=q,k;for(k in d){var n=a.j[k],f=d[k],o=!1;if(a.d.t>0&&g.length>0)for(var p=0;p<g.length;p++){var r=g[p],s=0,s=f>r.d.O?Ma(a.d,r.d.O):Ma(a.d,f);h+=s;f-=s;r.d.O-=s;r.d.O==0&&(g.splice(p,1),p--);if(f==0){o=!0;break}}if(!o){f/=b*1;if(v(0,100)<Math.round(f*100))f=".",a.d.t<=0&&g.length!=0&&(f=", insufficient Gold to ship Food."),
n.ea=Na,e.push(new M(Oa,n,"Riots over food shortages killed one population on planet: "+n.m+f)),n.r.length>0&&n.r.pop();else if(n.r.length>0)n.ea=Pa,o=n.r[n.r.length-1],o.cb-=f,o.cb<=-1?(e.push(new M(Qa,n,"You lost one population due to food shortages on planet: "+n.m)),n.r.pop()):(j++,i!=""&&(i+=", "),i+=n.m,l=n);n.r.length==0&&(e.push(new M(Ra,n,"You have lost control of "+n.m+" due to starvation")),Ca(n,q),Fa(n,a))}}j>0&&(d=".",a.d.t<=0&&g.length!=0&&(d=", insufficient Gold to ship Food."),g="planet: ",
j>1&&(g="planets: "),e.push(new M(Sa,l,"Population unrest over lack of Food on "+g+i+d)));h!=0&&e.push(new M(Ta,q,"You spent "+h+" Gold shipping Food."));return e}function ta(a){var b=[],e;for(e in a.j){var d=a.j[e],g={buildQueueEmpty:!1},b=b.concat(Ua(d,g));g.buildQueueEmpty&&d.f.xa>0&&(a.d.da+=d.f.xa/4,a.d.Ba())}return b}
function va(a){var b=[],e;for(e in a.j){var d=a.j[e],g=d.r.length;if(g>0&&d.ea!=Na&&(g<Va(d)||d.r[g-1].cb<1)){var h=g/4*((Va(d)-g)/8);d.ea==Pa&&(h/=2);g=d.r[g-1];g.cb+=h;if(g.cb>=1)b.push(new M(Wa,d,"Population growth on planet: "+d.m)),g.cb=0,d.r.push(new Xa(d.c)),Ya(d.f)}}return b}
var Za=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128,0,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128,0,255,0,128,0,255,0,128,0,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128,0,255,0,0,0,0,0,0,0,0,0,0,0,0,0,128,0,255,0,128,0,255,0,128,0,255,0,0,0,0,0,0,0,0,0,0,0,0,0,128,0,255,0,128,0,255,0,0,0,0,0,0,0,0,0,0,0,0,0,128,0,255,0,128,0,255,0,128,0,255,0,0,0,0,0,0,0,0,0,0,0,0,0,128,0,255,0,128,0,255,0,128,0,255,0,0,0,0,0,0,0,0,0,128,0,255,0,128,0,255,0,128,0,255,0,0,0,0,0,
0,0,0,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,0,0,0,0,0,0,0,0,128,0,255,0,128,0,255,0,128,0,255,0,0,0,0,0,0,0,0,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,0,0,0,0,128,0,255,0,128,0,255,0,128,0,255,0,0,0,0,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,0,0,0,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,
255,0,128,0,255,0,0,0,0,0,0,0,0,0,0,0,0,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128,0,255,0,128,0,255,0,0,0,0,0,128,0,255,0,128,0,255,0,0,0,0,0,0,0,0,0,0,0,0],$a=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128,0,255,0,128,0,255,0,128,0,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,0,0,0,0,0,0,0,0,0,0,0,0,128,0,255,0,128,0,255,0,128,
0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,0,0,0,0,0,0,0,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,0,0,0,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,0,0,0,0,0,0,0,0,0,0,0,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128,0,255,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128,0,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,128,0,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128,0,255,0,128,0,255,0,128,0,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128,0,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];
function ab(a,b){for(var e=Array(a.length),d=0;d<a.length;d+=4)a[d+3]!=0?(e[d+0]=b.Bc,e[d+1]=b.wc,e[d+2]=b.sc):(e[d+0]=a[d+0],e[d+1]=a[d+1],e[d+2]=a[d+2]),e[d+3]=a[d+3];return e}function bb(a,b,e,d){this.Bc=a;this.wc=b;this.sc=e;this.Qc=d}bb.prototype.toString=function(){return"rgba("+this.Bc+", "+this.wc+", "+this.sc+", "+this.Qc+")"};var cb=q,db=q,eb=q,fb=q,gb=q,N=q,hb=q,ib=q,jb=[],kb=0,lb={},mb=[],nb=["white","yellow","orange","blue","green","red","purple"],ob=!1,pb=q,qb=q;
$(document).ready(function(){rb();cb=new jCanvas({containerSelector:"#canvasContainer",canvasNotSupportedCallback:sb,layers:[{name:"canvasAstriarchBackground",x:0,y:0,width:800,height:600,zIndex:1,backgroundColor:"black"},{name:"canvasAstriarchPlayfield",x:177,y:5,width:615,height:480,zIndex:2,clickCallback:tb,dblclickCallback:ub,mouseHitSelector:"#canvasMouseHitDetector"},{name:"canvasAstriarchFleets",x:177,y:5,width:615,height:480,zIndex:3,clickCallback:vb,mouseHitSelector:"#canvasMouseHitDetector"}]});
if(cb.canvasSupported){var a=cb.getLayer("canvasAstriarchBackground");gb=a.canvas;N=a.ctx;hb=cb.getLayer("canvasAstriarchPlayfield");ib=cb.getLayer("canvasAstriarchFleets");hb.canvas.dblclick(function(){});setTimeout(function(){wb()},10);N.globalAlpha=1;setInterval(function(){cb.draw()},50);db=new AudioInterface}});
function sb(){$("#startGameOptionsContainer").hide();$("#canvasContainer").html('<p style="color:white">Astriarch HTML 5 version not supported by your browser.  You can play the silverlight plugin by clicking <a href="silverlight.html">here</a>. In 5 seconds you will be taken to the silverlight version automatically.</p>');setTimeout(function(){window.location="silverlight.html"},5E3)}function xb(){lb={};mb=[];hb.children=[];ib.children=[];hb.needsDisplay=!0;ib.needsDisplay=!0}
function yb(){var a=Number($("input:radio[name=OpponentCountRadioGroup]:checked").val());$("#Computer2Panel").hide();$("#Computer3Panel").hide();$("#StarfieldPanel1").show();$("#StarfieldPanel2").show();a>=2&&($("#Computer2Panel").show(),$("#StarfieldPanel1").hide(),$("#StarfieldRadio2").prop("checked",!0));a>=3&&($("#Computer3Panel").show(),$("#StarfieldPanel2").hide(),$("#StarfieldRadio3").prop("checked",!0))}
function Ab(){$("#startGameOptionsContainer").show();xb();$("#TurnDisplay,#OverallPlayerStatusGrid,#SelectedItemStatus,#SelectedItemPopulationPanel,#SelectedItemImprovementSlotsPanel,#SelectedItemPopulationAssignmentsPanel,#SelectedItemBuiltImprovementsGrid,#SelectedItemPlanetaryFleetGrid,#BottomStatusGrid,#TurnSummaryItemsListBox,#ButtonPanel").hide();$("#PlanetViewButton,#SendShipsButton,#NextTurnButton").hide()}
function rb(){$("#NewSkirmishGameButton").button();$("#NewCampaignGameButton").hide();$("#ResumeGameButton").button();$("#ResumeGameButton").button("disable");Bb()&&$("#ResumeGameButton").button("enable");$("#NewSkirmishGameButton").click(function(){$("#mainMenu").hide();Ab()});$("#ResumeGameButton").click(function(){$("#mainMenu").hide();var a=!1;if(localStorage){var b=localStorage.getItem("astriarch_save");if(b!=q)try{var e=JSON.parse(b),b=[],d=new Cb(b,q,e.Sa,e.bb,!0);d.Ia=e.Ia;d.V=jQuery.extend(d.V,
e.V);var g=[],h={},i;for(i in e.Wb){var f=e.Wb[i],j=new Db(f.c,f.m,Eb(d.J,f.sa),q);j.b=f.b;j.r=f.r;j.Ha=f.Ha;for(var l in f.p){var k=Fb(f.p[l]);j.p.push(k)}j.g=f.g;j.Z=f.Z;j.d=jQuery.extend(j.d,f.d);j.sa=f.sa;j.k=Gb(f.Kc,d);for(l in f.Rb)j.ta.push(Gb(f.Rb[l],d));j.ea=f.ea;j.za=f.za;j.Ca=f.Ca;j.f=new Hb(j,j.c);j.zc=j.Z;g.push(j);h[j.b]=j}for(i in e.lb)b.push(Ib(d,e.lb[i],h));var k={},n=q;for(i in b){var o=b[i];o.c==ma&&(n=o);k[o.b]=o}for(i in e.Xb)o=e.Xb[i],k[o.b]=Ib(d,o,h);for(i in e.lb)for(l in f=
e.lb[i],j=k[f.b],f.Pb){var p=f.Pb[l],r=Gb(p.Nc,d),s=new Jb(r,q);s.Ja=p.Ja;if(p.ec)s.Ea=k[p.ec];j.B[l]=s}d.H=n;d.U=g;d&&d.H&&(u=d,a=!0)}catch(D){a=!1}}a?(Kb(),$("#TurnDisplay,#OverallPlayerStatusGrid,#SelectedItemStatus,#SelectedItemPopulationPanel,#SelectedItemImprovementSlotsPanel,#SelectedItemPopulationAssignmentsPanel,#SelectedItemBuiltImprovementsGrid,#SelectedItemPlanetaryFleetGrid,#BottomStatusGrid,#TurnSummaryItemsListBox,#ButtonPanel").show(),$("#PlanetViewButton,#SendShipsButton,#NextTurnButton").show()):
(alert("There was an error loading your saved game, you will have to start a new game instead."),Ab())});$("select#Computer1DifficultyComboBox").selectmenu({style:"popup",width:90});$("select#Computer2DifficultyComboBox").selectmenu({style:"popup",width:90});$("select#Computer3DifficultyComboBox").selectmenu({style:"popup",width:90});$("select#PlanetsPerSystemComboBox").selectmenu({style:"popup",width:55});$("#OpponentCountRadio1").change(function(){yb()});$("#OpponentCountRadio2").change(function(){yb()});
$("#OpponentCountRadio3").change(function(){yb()});$("#StartGameOptionsOkButton").button();$("#StartGameOptionsOkButton").click(function(){$("#TurnDisplay").text("Turn 1, Year 3001");var a=[],b=$("#PlayerNameTextBox").val();if(b==q||$.trim(b)=="")b="Player1";b=new Lb(ma,b);a.push(b);a.push(new Lb(Number($("select#Computer1DifficultyComboBox").selectmenu("value")),"Computer 1"));var e=Number($("input:radio[name=OpponentCountRadioGroup]:checked").val());e>1&&a.push(new Lb(Number($("select#Computer2DifficultyComboBox").selectmenu("value")),
"Computer 2"));e>2&&a.push(new Lb(Number($("select#Computer3DifficultyComboBox").selectmenu("value")),"Computer 3"));var d=Number($("input:radio[name=StarfieldRadioGroup]:checked").val()),g=Number($("select#PlanetsPerSystemComboBox").selectmenu("value"));u=new Cb(a,b,d,g);Kb();AstriarchExtern.OnGameStart({Players:e+1,PlanetsPerSystem:g,Systems:d});$("#startGameOptionsContainer").hide();$("#TurnDisplay,#OverallPlayerStatusGrid,#SelectedItemStatus,#SelectedItemPopulationPanel,#SelectedItemImprovementSlotsPanel,#SelectedItemPopulationAssignmentsPanel,#SelectedItemBuiltImprovementsGrid,#SelectedItemPlanetaryFleetGrid,#BottomStatusGrid,#TurnSummaryItemsListBox,#ButtonPanel").show();
$("#PlanetViewButton,#SendShipsButton,#NextTurnButton").show()});qb=new JSListBox({containerSelector:"TurnSummaryItemsListBox",stylemap:{border:"none",background:"none"}});$("#PlanetViewButton, #SendShipsButton, #NextTurnButton, #CancelSendButton, #MainMenuButtonGameOver").button();$("#CancelSendButton").hide();$("#MainMenuButtonGameOver").hide();$("#SystemMasterVersion").text("v1.2.1");$("#SystemMasterVersion").attr("Title","Astriarch - Ruler of the Stars, Version: 1.2.1\r\nCopyright 2010 Mastered Software\r\nMusic by Resonant");
Mb();Nb();Ob=new Pb("#planetaryConflictDialog","Planetary Conflict",424,323,Qb,Rb);Sb=new Pb("#gameOverDialog","Game Over",424,313,Tb,Ub);$("#PlanetViewButton").click(function(){Vb(u.J.ja.R)});$("#SendShipsButton").click(function(){ob=!0;$("#SendShipsStatus").text(" Select Planet to Send Ships to. ");$("#CancelSendButton").show();pb=u.J.ja});$("#NextTurnButton").click(function(){if(localStorage){var a=new Wb(u),a=JSON.stringify(a);a!=q&&localStorage.setItem("astriarch_save",a)}u.V.ka++;a=u.V.ka+3E3;
$("#TurnDisplay").text("Turn "+u.V.ka+", Year "+a);var b=u.S,a=[],e;for(e in b){var d=b[e];if(d.c!=ma){var g;g=d;var h=[],i=m;for(i in g.j)h.push(g.j[i]);h.sort(Xb);g=h;var h=d,f=g,j=[],l=[],i=[],k=m;for(k in f){var n=f[k];h.v[n.b]||n.p.length<=1&&(Yb(n)<n.Z?j.push(n):Zb(h)!=0?i.push(n):n.g[B].length==0?l.push(n):i.push(n))}for(k in l)n=l[k],$b(n,B)==0&&(h.v[n.b]=new P(B));for(k in j){var n=j[k],l=f=0,o=1;n.c==ga?(f=3,l=2,o=3):n.c==fa?o=f=2:n.c==ea?l=1:n.c==w&&(l=1);$b(n,z)<f?h.v[n.b]=new P(z):$b(n,
A)<l?h.v[n.b]=new P(A):$b(n,x)==0?h.v[n.b]=new P(x):$b(n,y)==0?h.v[n.b]=new P(y):$b(n,x)<o?h.v[n.b]=new P(x):Yb(n)<n.Z&&(h.v[n.b]=new P(y))}for(k in i)f=j=!1,h.c==bc?(j=v(0,4)<=1,f=!j&&v(0,4)<=1):h.c==cc&&(j=v(0,4)==0,f=!j&&v(0,4)==0),n=i[k],n.g[B].length>0&&!j?(j=v(4),h.v[n.b]=j<2?j%2==0?new J(I):new J(G):j%2==1?new J(H):new J(G)):Zb(h)!=0?h.v[n.b]=new J(F):n.g[x].length>0&&f?h.v[n.b]=new J(G):u.V.ka%4==0&&j&&(h.v[n.b]=new J(E));h=d;i=g;k=h.Fa;switch(h.c){case bc:k=v(0,(k+1)/4);break;case cc:k=v(0,
(k+1)/2);break;case dc:k+=aa(h.j)-0.5;break;case ec:k+=aa(h.j)-0.25}n=m;for(n in i)j=i[n],j.p.length==0&&j.b in h.v&&(l=h.v[j.b],h.d.t-l.u>k&&na(h)-l.D>=0&&oa(h)-l.G>=0&&(f=j,o=h,f.p.push(l),pa(f,l.u,l.D,l.G,o),delete h.v[j.b]));o=d;h={};i={};k={};n=[];j=m;for(j in o.j)f=o.j[j],l=new qa,ra(f,l),h[f.b]=l.Xa,i[f.b]=l.Ra,k[f.b]=l.ib,n.push(f);var p=la(o),r=0,s=0,l=0;for(j in o.j)f=o.j[j],s+=f.d.O,r+=f.f.Ya,f.r.length<Va(f)&&l++;s-=p;s-=l;l=f=0;switch(o.c){case bc:f-=p*3;l=Math.floor(p*1.5);break;case cc:f-=
Math.floor(p*1.5);l=p;break;case dc:f-=p/2,l=0}s+=v(f,l+1);var D=l=0;for(j in o.j)f=o.j[j],f.b in o.v&&(f=o.v[f.b],l+=f.D,D+=f.G);f=1;switch(o.c){case bc:f=v(20,41)/10;break;case cc:f=v(10,21)/10}l=Math.round(l*f)-na(o);o=Math.round(D*f)-oa(o);if(p>r+s){r=p-(r+s);n.sort(fc);p=r;s=[];if(p>0)for(j in n)if(f=n[j],p>0&&gc(f.f)>0&&(i[f.b]>0||k[f.b]>0))if(s.push(f),p-=gc(f.f),p<=0)break;for(;r>0;){p=!1;for(j in s)if(f=s[j],D=k[f.b],f.c==ga&&(D=f.g[A].length==0?0:1),i[f.b]>=D&&i[f.b]>0?(hc(f,h[f.b],i[f.b],
k[f.b],1,-1,0),h[f.b]++,i[f.b]--,r-=gc(f.f),p=!0):k[f.b]>0&&(hc(f,h[f.b],i[f.b],k[f.b],1,0,-1),h[f.b]++,k[f.b]--,r-=gc(f.f),p=!0),r<=0)break;if(!p)break}}else{r=r+s-p;n.sort(fc);n.reverse();p=r;s=[];if(p>0)for(j in n)if(f=n[j],p>0&&p>gc(f.f)&&h[f.b]>0&&(s.push(f),p-=gc(f.f),p<=0))break;for(;r>0;){p=!1;for(j in s)if(f=s[j],!(r<gc(f.f))&&((f.c!=ga||f.g[A].Yc>0)&&(l>0||o>0)&&h[f.b]>0?(hc(f,h[f.b],i[f.b],k[f.b],-1,1,0),h[f.b]--,i[f.b]++,l-=ic(f.f),o-=jc(f.f),r-=gc(f.f),p=!0):h[f.b]>0&&(hc(f,h[f.b],i[f.b],
k[f.b],-1,0,1),h[f.b]--,k[f.b]++,r-=gc(f.f),p=!0),r<=0))break;if(!p)break}}if(l>0||o>0){p=l*1;s=o*1;r=[];f=new kc(l,o);n.sort(f.W);if(p>0||s>0)for(j in n){var f=n[j],D=0,K=-1;f.c==ga&&(D=f.g[A].length==0?2:1,K=0);k[f.b]>D&&h[f.b]>K&&(r.push(f),p-=ic(f.f),s-=jc(f.f))}for(;l>0||o>0;){p=!1;for(j in r)if(f=r[j],D=1,f.g[A].length==0&&(D=2),k[f.b]>D&&(hc(f,h[f.b],i[f.b],k[f.b],0,1,-1),i[f.b]++,k[f.b]--,l-=ic(f.f),o-=jc(f.f),p=!0),l<=0&&o<=0)break;if(!p)break}}else{p=Math.abs(l*1)/2;s=Math.abs(o*1);r=[];
f=new kc(l,o);n.sort(f.W);n.reverse();if(p>0||s>0)for(j in n)f=n[j],i[f.b]>0&&(r.push(f),p-=ic(f.f),s-=jc(f.f));for(;l<=0||o<=0;){p=!1;for(j in r)if(f=r[j],i[f.b]>0&&(hc(f,h[f.b],i[f.b],k[f.b],0,-1,1),i[f.b]--,k[f.b]++,l+=ic(f.f),o+=jc(f.f),p=!0),l>0&&o>0)break;if(!p)break}}i=g;g=[];h=m;for(h in i)if(k=i[h],lc(k.k)>0)if(d.c==bc)g.push(k);else{n=0;Zb(d)!=0?n=0:k.g[x].length>0&&(n=Math.floor(Math.pow(k.c,2)*4));if(d.c==dc||d.c==ec){j={minDistance:0};f=d;l=k;o=j;o.minDistance=999;p=q;r=m;for(r in u.U)if(s=
u.U[r],s.b!=l.b&&s.q!=f&&(D=mc(l.o,s.o),D<o.minDistance))o.minDistance=D,p=s;f=p;f!=q&&(d.B[f.b]?n+=L(d.B[f.b].fa,!1):d.va[f.b]&&(n+=Math.floor(Math.pow(f.c,2)*4)));f={turnsToComplete:99,starshipStrength:0};a:{l=k;o=f;o.turnsToComplete=99;o.starshipStrength=0;p=m;for(p in l.p)if(r=l.p[p],r instanceof J&&r.c!=E){o.turnsToComplete=r.zb;o.starshipStrength=(new Q(r.c)).Na;l=!0;break a}l=!1}l&&f.turnsToComplete<=j.minDistance+1&&(n-=f.starshipStrength)}L(k.k)>n&&g.push(k)}i=[];n=[];if(g.length>0)for(h in u.U)k=
u.U[h],k.q!=d&&!nc(d,k)&&(!d.va[k.b]||d.c!=bc&&d.B[k.b]&&u.V.ka-d.B[k.b].Ja>20?i.push(k):oc(d,k)||n.push(k));d.Qa!=q&&(k=d.c==bc||d.c==cc?new pc(d.Qa):new qc(d.Qa,d.B),n.sort(k.W),i.sort(k.W));j=[];if(d.c==ec)for(h in d.j)k=d.j[h],k.g[x].length>0&&j.push(k);for(h=n.length-1;h>=0;h--){f=n[h];d.c==bc||d.c==cc?(k=new pc(f),g.sort(k.W)):(k=new qc(f,d.B),g.sort(k.W),g.reverse());k=0.5;l=1;switch(d.c){case bc:k=3;l=6;break;case cc:k=2;l=4;break;case dc:k=1,l=2}for(var K=v(Math.floor(k*10),Math.floor(l*
10)+1)/10,ua=!1,l=g.length-1;l>=0;l--){var k=g[l],ld=Math.floor(Math.pow(f.c+1,2)*4);d.B[f.b]&&(ld=L(d.B[f.b].fa));p=k.k.a[F].length;r=k.k.a[G].length;s=k.k.a[H].length;D=k.k.a[I].length;o=rc(0,p,r,s,D,k.o);if(L(o)>ld*K){o=sc(k.k,p,r,s,D);o.mb(k.o,f.o);k.ta.push(o);k=lc(k.k);k==0&&g.splice(l,1);ua=!0;break}}if(!ua&&j.length>0){k=new pc(f);j.sort(k.W);K=j[j.length-1];o=mc(f.o,K.o);for(l=g.length-1;l>=0;){k=g[l];if(k.b==K.b)break;if(mc(f.o,k.o)<o)break;p=k.k.a[F].length;r=k.k.a[G].length;s=k.k.a[H].length;
D=k.k.a[I].length;rc(0,p,r,s,D,k.o);o=sc(k.k,p,r,s,D);o.mb(k.o,K.o);k.ta.push(o);k=lc(k.k);k==0&&g.splice(l,1);break}}if(g.length==0)break}if(g.length>0)for(h=i.length-1;h>=0;h--){f=i[h];d.c==bc||d.c==cc?(k=new pc(f),g.sort(k.W)):(k=new qc(f,d.B),g.sort(k.W),g.reverse());for(l=g.length-1;l>=0;){k=g[l];n=i[h];j=k.k;f=q;s=r=p=o=0;j.a[F].length!=0?o=1:j.a[G].length!=0?p=1:j.a[H].length!=0?r=1:j.a[I].length!=0&&(s=1);if(o!=0||p!=0||r!=0||s!=0)f=sc(j,o,p,r,s);o=f;o.mb(k.o,n.o);k.ta.push(o);k=lc(k.k);k==
0&&g.splice(l,1);break}if(g.length==0)break}}}for(e in b){d=b[e];g=m;for(g in d.ga)tc(d.ga[g]);h=m;for(h in d.j){i=d.j[h];for(g=i.ta.length-1;g>=0;g--)k=i.ta[g],d.ga.push(k),tc(k),i.ta.splice(g,1)}for(g=d.ga.length-1;g>=0;g--)if(i=d.ga[g],i.X.aa==0)k=i.ca.R,k.q==d?Ea(k.k,i,i.ca):(h=d,h.jb[k.b]?uc(h.jb[k.b],i):h.jb[k.b]=i),d.ga.splice(g,1)}for(e in b)d=b[e],d==u.H?a=a.concat(ja(d)):ja(d);for(e in u.U){d=u.U[e].k;d.la=0;g=m;for(g in d.a[E])d.a[E][g].qa=0;for(g in d.a[F])d.a[F][g].qa=0;for(g in d.a[G])d.a[G][g].qa=
0;for(g in d.a[H])d.a[H][g].qa=0;for(g in d.a[I])d.a[I][g].qa=0}for(e in b)a=a.concat(wa(b[e]));a.sort(vc);b=!1;e=[];for(var C in u.S)d=u.S[C],aa(d.j)==0&&d.ga.length==0&&(e.push(d),d==u.H&&(b=!0));for(var zb in e){d=e[zb];for(C=u.S.length-1;C>=0;C--)u.S[C]==d&&u.S.splice(C,1)}if(u.S.length>1&&!b)for(C in e){var O=e[C];new wc(O.m+" Destroyed",'Player: <span style="color:'+O.ba.toString()+'">'+O.m+"</span> destroyed.")}else{C=u.S[0];db.EndGame();zb=C==u.H;$("#PlanetViewButton,#SendShipsButton,#NextTurnButton").hide();
e=u.H;b=0;b=u.V.ka;b>1E3&&(b=1E3);d=u.Sa;g=d*Math.floor(u.bb)-8;for(O in u.S)h=u.S[O],h.c==bc?g+=1:h.c==cc?g+=2:h.c==dc?g+=3:h.c==ec&&(g+=4);O=aa(e.j);O==0&&(O=1);e=la(e);e==0&&(e=1);O=b=Math.round(g*1/(b*1)*g*O+e*d);e="";e+=zb?"You conquered all of your enemies and reign supreme over the known universe!<br />You will be known as the first Astriarch - Ruler of the Stars.<br />":"You lost control over all your fleets and planets and have been crushed by the power of your enemies!<br />";e+="In "+u.V.ka+
" turns.<br />";e+=C.m+" won the game with "+aa(C.j)+" planets.<br />";e+="<br />Your points: "+O;AstriarchExtern.OnGameOver({PlayerWon:zb,Turns:u.V.ka,Score:O});$("#GameOverSummary").html(e);xc(Sb,"Game Over, Player: "+C.m+" Wins!");Sb.open()}yc=[];if(u.H.wa.nb)for(var ac in a)C=a[ac],(C.c==Ja||C.c==Ka||C.c==Ga||C.c==Ia)&&C.I!=q&&yc.push(C);zc();Ac();Bc();qb.clear();if(a.length>0){O=[];for(ac in a){C=a[ac];C=new Cc(C);switch(C.ra.c){case Ta:case Wa:C.L="blue";break;case Ka:C.L="purple";break;case Dc:case Sa:C.L=
"yellow";break;case Ga:case Ja:C.L="orange";break;case Ia:case Qa:case Ra:case Oa:C.L="red";break;default:C.L="green"}O.push(C)}qb.addItems(O);Ec()}});$("#CancelSendButton").click(function(){Fc()});$("#MainMenuButtonGameOver").click(function(){Gc()});$("#MainMenuButton").button({icons:{primary:"MainMenuButton"},text:!1});$("#MainMenuButton").click(function(){Gc()});$("#MainMenuIcon").mouseenter(function(){$("#MainMenuIcon").hide();$("#MainMenuButton").show()});$("#MainMenuButton").mouseleave(function(){$("#MainMenuButton").hide();
$("#MainMenuIcon").show()});$("#SpeakerIcon").mouseenter(function(){$("#SpeakerIcon").hide();$("#ButtonSpeakerToggleMute").show();clearTimeout(fb);eb=setTimeout(Hc,200)});$("#ButtonSpeakerToggleMute").mouseleave(function(){$("#ButtonSpeakerToggleMute").hide();$("#SpeakerIcon").show();fb=setTimeout(Ic,200)});$("#SliderVolume").mouseenter(function(){clearTimeout(fb)});$("#SliderVolume").mouseleave(function(){fb=setTimeout(Ic,200)});$("#ButtonSpeakerToggleMute").button({icons:{primary:"SpeakerImgOn"},
text:!1});$("#ButtonSpeakerToggleMute").click(function(){db.toggleMute();db.muted?($("#SpeakerIcon").css("background-image",'url("img/ico_speaker_off.png")'),$("#ButtonSpeakerToggleMute > .ui-icon").removeClass("SpeakerImgOn").addClass("SpeakerImgOff")):($("#SpeakerIcon").css("background-image",'url("img/ico_speaker_on.png")'),$("#ButtonSpeakerToggleMute > .ui-icon").removeClass("SpeakerImgOff").addClass("SpeakerImgOn"))});$("#SliderVolume").slider({value:1,step:0.1,min:0,max:1,orientation:"vertical",
slide:Jc})}function Gc(){db.StartMenu();$("#MainMenuButtonGameOver").hide();$("#MainMenuButton").hide();$("#mainMenu").show()}function Fc(){$("#SendShipsStatus").text("");$("#CancelSendButton").hide();ob=!1}function Kc(a){a==!0&&Lc!=q&&lc(Mc.k)==0&&lb[Mc.b].pc(u.H);Nc(u.J,Mc.o);Ac()}
function tb(a){a=Eb(u.J,new R(a.x,a.y));if(a!=q&&a.R!=q&&(Nc(u.J,a),Ac(),ob)){if(pb!=u.J.ja){var a=pb.R,b=u.J.ja.R,e=mc(pb,u.J.ja);Lc=q;Mc=a;Oc=b;$("#SendShipsDialogStatus").text(e+" parsecs from "+a.m+" to "+b.m);e=a.k;$("#SliderScouts").slider("value",0);$("#SliderScouts").slider("option","max",e.a[F].length);$("#SliderScouts").slider("option","max")>0?$("#SliderScouts").slider("enable"):$("#SliderScouts").slider("disable");$("#SliderDestroyers").slider("value",0);$("#SliderDestroyers").slider("option",
"max",e.a[G].length);$("#SliderDestroyers").slider("option","max")>0?$("#SliderDestroyers").slider("enable"):$("#SliderDestroyers").slider("disable");$("#SliderCruisers").slider("value",0);$("#SliderCruisers").slider("option","max",e.a[H].length);$("#SliderCruisers").slider("option","max")>0?$("#SliderCruisers").slider("enable"):$("#SliderCruisers").slider("disable");$("#SliderBattleships").slider("value",0);$("#SliderBattleships").slider("option","max",e.a[I].length);$("#SliderBattleships").slider("option",
"max")>0?$("#SliderBattleships").slider("enable"):$("#SliderBattleships").slider("disable");xc(Pc,"Sending Ships from "+a.m+" to "+b.m);Pc.open()}Fc()}return!0}function ub(a){a=Eb(u.J,new R(a.x,a.y));a!=q&&a.R!=q&&a.R.q==u.H&&Vb(u.J.ja.R);return!0}function vb(){return!0}
function zc(){var a=u.H;if(a!==q){$("#OverallPlayerStatusGrid").css({visibility:"visible"});var b=la(a);$("#TextBlockPopulationAmount").text(b);var e;e=0;for(var d in a.j)e+=a.j[d].d.O;d=0;for(var g in a.j)d+=a.j[g].f.Ya;g=d-b;d="";g>=0&&(d="+");var h="green";g<0?h=g+e<b?"red":"yellow":g+e<b&&(h="orange");$("#TextBlockFoodAmount").css("color",h);$("#TextBlockFoodAmount").text(e+" "+d+g);$("#TextBlockGoldAmount").text(a.d.t);$("#TextBlockOreAmount").text(na(a));$("#TextBlockIridiumAmount").text(oa(a))}}
function Ac(){$("#PlanetViewButton").button("disable");$("#SendShipsButton").button("disable");var a="";if(u.J.ja!=q){var b=u.J.ja.R,e=u.H;a+="--- Planet "+b.m+" ---<br />";$("#SelectedItemBuiltImprovementsGrid").css({visibility:"hidden"});$("#SelectedItemPlanetaryFleetGrid").css({visibility:"hidden"});$("#SelectedItemPopulationPanel").css({visibility:"hidden"});$("#SelectedItemPopulationAssignmentsPanel").css({visibility:"hidden"});$("#SelectedItemImprovementSlotsPanel").css({visibility:"hidden"});
if(Qc(e,b)){var d=q,g=q;if(e.B[b.b])d=e.B[b.b],g=d.Ea;a+=da(b.c)+"<br />";if(b.q==e||u.Ia){d=b.c==w?"None":"Natives";if(b.q!=q)d=b.q.m;a+=d+"<br />";$("#SelectedItemBuiltImprovementsGrid").css({visibility:"visible"});$("#SelectedItemPlanetaryFleetGrid").css({visibility:"visible"});$("#SelectedItemPopulationPanel").css({visibility:"visible"});$("#SelectedItemPopulationAssignmentsPanel").css({visibility:"visible"});$("#SelectedItemImprovementSlotsPanel").css({visibility:"visible"});d=b.r.length;g=Va(b);
$("#SelectedItemPopulationPanel").attr("Title","Planet Population: "+d+" / "+g);for(var h=g+1;h<=16;h++)$("#PopulationImage"+h).css("background-image","");for(h=1;h<=g;h++)h<=d?$("#PopulationImage"+h).css("background-image","url(img/PopulationSmallFilled.png)"):$("#PopulationImage"+h).css("background-image","url(img/PopulationSmallEmpty.png)");var d=b.g[z].length,g=b.g[A].length,h=b.g[y].length,i=b.g[x].length,f=b.g[B].length,j=d+g+i+h,l=b.Z;$("#SelectedItemImprovementSlotsPanel").attr("Title","Planetary Improvements: "+
j+" / "+l);for(var k=l+1;k<=9;k++)$("#PlanetaryImprovementSlotsImage"+k).css("background-image","");for(k=1;k<=l;k++)k<=j?$("#PlanetaryImprovementSlotsImage"+k).css("background-image","url(img/PlanetaryImprovementSlotFilled.png)"):$("#PlanetaryImprovementSlotsImage"+k).css("background-image","url(img/PlanetaryImprovementSlotEmpty.png)");ra(b,new qa);$("#SelectedItemPopulationAssignmentsPanel").attr("Title",farmers+(farmers==1?" Farmer, ":" Farmers, ")+miners+(miners==1?" Miner, ":" Miners, ")+workers+
(workers==1?" Workers":" Workers"));for(j=farmers+miners+workers+1;j<=16;j++)$("#PopulationAssignmentImage"+j).css("background-image","");for(j=1;j<=farmers;j++)$("#PopulationAssignmentImage"+j).css("background-image","url(img/Farmer.png)");for(j=farmers+1;j<=farmers+miners;j++)$("#PopulationAssignmentImage"+j).css("background-image","url(img/Miner.png)");for(j=farmers+miners+1;j<=farmers+miners+workers;j++)$("#PopulationAssignmentImage"+j).css("background-image","url(img/Builder.png)");$("#TextBlockFarmCount").text(d);
$("#TextBlockMineCount").text(g);$("#TextBlockFactoryCount").text(i);$("#TextBlockColonyCount").text(h);$("#TextBlockSpacePlatformCount").text(f);d=b.k.a[F].length;g=b.k.a[G].length;h=b.k.a[H].length;i=b.k.a[I].length;$("#TextBlockDefenderCount").text(b.k.a[E].length);$("#TextBlockScoutCount").text(d);$("#TextBlockDestroyerCount").text(g);$("#TextBlockCruiserCount").text(h);$("#TextBlockBattleshipCount").text(i);b.q==e&&($("#PlanetViewButton").button("enable"),(d!=0||g!=0||h!=0||i!=0)&&$("#SendShipsButton").button("enable"))}else if(d!=
q)a+=ca(b,g)+"<br />",b=d.fa,e=u.V.ka-d.Ja,a+="--- Known Fleet ---<br />",a+=(e==0?"Explored this turn.":e==1?"Explored last turn.":"As of "+e+" turns ago.")+"<br />",a+=b.F?"1 Space Platform<br />":"No Space Platform<br />",$("#TextBlockDefenderCount").text(b.a[E].length),$("#TextBlockScoutCount").text(b.a[F].length),$("#TextBlockDestroyerCount").text(b.a[G].length),$("#TextBlockCruiserCount").text(b.a[H].length),$("#TextBlockBattleshipCount").text(b.a[I].length),$("#SelectedItemPlanetaryFleetGrid").css({visibility:"visible"})}else a+=
"Unexplored"}$("#SelectedItemStatus").html(a)}function Bc(){for(var a in lb)lb[a].pc(u.H);hb.needsDisplay=!0}
function wb(){for(var a=0;a<7;a++){var b=new Image;b.onload=function(){kb++;if(kb>=7){for(var a=Math.floor(gb[0].height/40),b=Math.floor(gb[0].width/40),g=[],h=[],i=0;i<a;i++)for(var f=0;f<b;f++)for(var j=v(0,20),l=0;l<j;l++){var k=v(0,40),n=v(0,40);if(l>=6||l%2==0){var o=v(10,71)/140,o=Math.floor(o*255);g.push(new Rc(f*40+n,i*40+k,o))}else h.push(new Rc(f*40+n,i*40+k,q))}a=N.createImageData(gb[0].width,gb[0].height);for(b=0;b<g.length;b++)i=g[b],f=(i.l+i.i*gb[0].width)*4,a.data[f]=255,a.data[f+1]=
255,a.data[f+2]=255,a.data[f+3]=i.Jc;N.putImageData(a,0,0);g={};for(a=0;a<7;a++)g[a]=100;a=Math.floor(gb[0].height/60);b=Math.floor(gb[0].width/80);for(i=0;i<a;i+=2)for(f=0;f<b;f+=2)if(v(0,2)==0){j=v(0,Math.floor(60));l=v(0,Math.floor(80));k=g;n=1;o=m;for(o in k)n+=k[o];var n=v(0,n),p=o=0,r=m;for(r in k){var s=k[r];if(n<s+o){p=r;k[r]=Math.floor(s/2);break}o+=s}k=p;N.globalAlpha=v(40,71)/100;N.drawImage(jb[k],f*80+l,i*60+j)}for(g=0;g<h.length;g++)a=h[g],b=v(1,6),i=b/2,f=N.createRadialGradient(a.l,
a.i,0,a.l,a.i,i),j=v(0,nb.length),f.addColorStop(0,"white"),f.addColorStop(0.5,nb[j]),f.addColorStop(1,"rgba(0, 0, 0, 0)"),N.globalAlpha=v(20,71)/100,N.fillStyle=f,N.fillRect(a.l-i,a.i-i,b,b);N.globalAlpha=1;N.lineWidth=2;N.strokeStyle="rgba(0, 128, 0, 255)";N.strokeRect(4,3,792,594);$("#loadingSpinner").hide();$("#mainMenu").show()}};b.src="img/backgrounds/"+a+".jpg";jb.push(b)}}function Rc(a,b,e){this.l=a;this.i=b;this.Jc=e}function Hc(){$("#SliderVolume").show()}
function Ic(){$("#SliderVolume").hide();clearTimeout(eb)}function Jc(a,b){db.setVolume(b.value)};function Sc(a,b){this.$a=[];this.ja=q;for(var e={},d=0,g=0;g+S.K.Pa<=b;g+=S.K.Pa/2){var h=0,i=0,f=0;d%2==1&&(f=(S.K.Ta-S.K.fb)/2+S.K.fb,i=1);for(;f+S.K.Ta<=a;f+=S.K.Ta+S.K.fb){var j=new S(Tc[d]+(i+1),f,g);j.Tb=i;this.$a.push(j);hb.addChild(j);e[i]||(e[i]=[]);e[i].push(j);h++;i+=2}d++}for(f in e)for(g in d=e[f],h=Math.floor(f/2)+f%2,d)j=d[g],j.Ub=h++}var Tc="ABCDEFGHIJKLMNOPQRSTUVWXYZ";function Nc(a,b){if(a.ja!=q)a.ja.Gc(),a.ja=q;b.Mc();a.ja=b}
function Eb(a,b){for(var e in a.$a)if(a.$a[e].Oa(b))return a.$a[e];return q}Sc.prototype.Oc=function(){};function mc(a,b){var e=a.Tb-b.Tb,d=a.Ub-b.Ub;return(Math.abs(e)+Math.abs(d)+Math.abs(e-d))/2};function R(a,b){this.l=a;this.i=b}function Uc(a,b,e,d){this.l=a;this.i=b;this.Ka=e;this.Da=d}function Vc(){this.Yb=this.Ab=this.rc=this.qc=m}
var S=jCanvas.DrawnObject.extend({init:function(a,b,e){this.$=[];var d=(S.K.Ta-S.K.fb)/2,g=S.K.Pa/2;this.$.push(new R(d+b,e));this.$.push(new R(d+S.K.fb+b,e));this.$.push(new R(S.K.Ta+b,g+e));this.$.push(new R(d+S.K.fb+b,S.K.Pa+e));this.$.push(new R(d+b,S.K.Pa+e));this.$.push(new R(b,g+e));this.b=a;this.x=b;this.y=e;this.gb=new R(this.x,this.y);this.Va=new R(this.x+S.K.Ta,this.y+S.K.Pa);this.T=new R(this.x+S.K.Ta/2,this.y+S.K.Pa/2);this.R=this.zIndex=this.Ub=this.Tb=q;this.selected=!1},draw:function(a){if(this.selected){a.strokeStyle=
"green";a.lineWidth=2;a.beginPath();a.moveTo(this.$[0].l,this.$[0].i);for(var b=1;b<this.$.length;b++){var e=this.$[b];a.lineTo(e.l,e.i)}a.closePath();a.stroke()}},isInBounds:function(a,b){return this.Oa(new R(a,b))},Mc:function(){this.selected=!0;this.layer.needsDisplay=!0},Gc:function(){this.selected=!1;this.layer.needsDisplay=!0},Wc:function(a){if(this.gb.l<a.l&&this.gb.i<a.i&&a.l<this.Va.l&&a.i<this.Va.i)return!0;return!1},Oa:function(a){var b=!1;if(this.Wc(a)){var e,d=0;e=0;for(d=this.$.length-
1;e<this.$.length;d=e++){var g=this.$[e],d=this.$[d];if((g.i<=a.i&&a.i<d.i||d.i<=a.i&&a.i<g.i)&&a.l<(d.l-g.l)*(a.i-g.i)/(d.i-g.i)+g.l)b=!b}}return b}});S.K={Pa:40,Ta:55,fb:25};function Cb(a,b,e,d,g){xb();this.Ia=!1;this.Sa=e;this.bb=d;this.V=new Wc;this.H=b;this.S=a;this.J=new Sc(615,480);this.U=[];this.Uc=615;this.Tc=480;this.Ga=[];this.Pc=[];b=a=0;e=this.Uc/2;d=this.Tc/2;this.Sa==2||this.Sa==4?(this.Ga.push(new Xc(a,b,e,d)),a=e,this.Ga.push(new Xc(a,b,e,d)),b=d,this.Ga.push(new Xc(a,b,e,d)),a=0):(this.Ga.push(new Xc(a,b,e,d)),this.Ga.push(new Xc(e,b,e,d)),a=e/2,b=d);this.Ga.push(new Xc(a,b,e,d));if(!g)for(g=0;g<this.Ga.length;g++){a=this.Ga[g];e=[];b=a.Ka/2;d=a.Da/2;
e.push(new Xc(a.l,a.i,b,d));var h=new Xc(a.l+b,a.i,b,d);g==1?e.splice(0,0,h):e.push(h);h=new Xc(a.l+b,a.i+d,b,d);g==2?e.splice(0,0,h):e.push(h);a=new Xc(a.l,a.i+d,b,d);g==3?e.splice(0,0,a):e.push(a);this.Pc.push(e);for(var i=[],a=[],b=0;b<e.length;b++)for(var f in d=e[b],i[b]=[],a[b]=[],this.J.$a)h=this.J.$a[f],d.fc!==h.gb.l&&d.nc!==h.gb.i&&d.mc!==h.Va.l&&d.$b!==h.Va.i&&d.Oa(h.gb)&&d.Oa(h.Va)?(i[b].push(h),a[b].push(h)):d.Oa(h.gb)&&d.Oa(h.Va)&&a[b].push(h);if(!(this.Sa==2&&(g==1||g==3))){var j=[];
j.push(fa);j.push(ea);j.push(w);for(b=0;b<e.length;b++){var d=v(0,i[b].length),d=i[b][d],l=3,h=ga;b>0&&j.length<=3&&(l=v(0,j.length),h=j[l],j.splice(l,1));var l=q,k=!1,n=0,o=Array(4);o[0]=new bb(0,128,0,255);o[1]=new bb(200,0,200,255);o[2]=new bb(0,0,255,255);o[3]=new bb(255,0,0,255);h==ga&&(g==0?k=!0:this.S.length==2?g==2&&(k=!0,n=1):g<this.S.length&&(k=!0,n=g));k&&(l=this.S[n],n!=0&&Yc(l,o[n]));d=new Db(h,d.b,d,l);if(l)d.d.C=2,d.d.A=1;this.U.push(d)}if(this.bb!=Zc)for(var l=j=i=e=25,k=50,n=34,o=
16,p=4;p<this.bb;p++)for(h=!1;!h;){var b=0,r=e+i+j+l;v(0,r)>e&&(b=1,v(0,r)>i&&(b=2,v(0,r)>j&&(b=3)));d=v(0,a[b].length);d=a[b][d];if(d.R==q){switch(b){case 0:e-=6;break;case 1:i-=6;break;case 2:j-=6;break;case 3:l-=6}h=fa;r=k+n+o;v(0,r)>o?(h=ea,v(0,r)>n?(h=w,k-=15):n-=15):o-=15;d=new Db(h,d.b,d,q);this.U.push(d);h=!0}}}}}function Xc(a,b,e,d){this.l=a;this.i=b;this.Ka=e;this.Da=d;this.fc=a;this.mc=a+e;this.nc=b;this.$b=b+d}
Xc.prototype.Oa=function(a){return this.fc<=a.l&&this.mc>=a.l&&this.$b>=a.i&&this.nc<=a.i?!0:!1};function Wc(){this.ka=1}var Zc=4;function Lb(a,b){this.b=$c++;this.c=a;this.m=b;this.d=new ad;this.ba=new bb(0,255,0,255);this.Ib=Za;this.Hb=$a;this.Fa=0;this.wa=new bd;this.j={};this.va={};this.B={};this.v={};this.Qa=q;this.ga=[];this.jb={}}var $c=1;function Yc(a,b){a.Ib=ab(a.Ib,b);a.Hb=ab(a.Hb,b);a.ba=b}function na(a){var b=0,e;for(e in a.j)b+=a.j[e].d.C;return b}function oa(a){var b=0,e;for(e in a.j)b+=a.j[e].d.A;return b}function oc(a,b){var e=!1;b.b in a.j&&(e=!0);return e}
function Qc(a,b){var e=u.Ia;b.b in a.va&&(e=!0);return e}function nc(a,b){for(var e in a.ga)if(a.ga[e].ca.R.b==b.b)return!0;return!1}function la(a){var b=0,e;for(e in a.j)b+=a.j[e].r.length;return b}function Zb(a){var b=0,e;for(e in u.U){var d=u.U[e];d.q!=a&&!nc(a,d)&&(!(d.b in a.va)||a.c!=bc&&d.b in a.B&&u.V.ka-a.B[d.b].Ja>20)&&b++}return b}var ma=0,bc=1,cc=2,dc=3,ec=4;function ad(){this.t=3;this.da=0}ad.prototype.Ba=function(){this.da>=1&&(this.t+=Math.floor(this.da/1),this.da%=1)};
function Ma(a,b){if(a.t>=b)return a.t-=b,b;else{var e=b-a.t;a.t=0;return e}}function bd(){this.Oc=!1;this.nb=!0};function Db(a,b,e,d){this.b=cd++;this.m=b;this.c=a;this.r=[];this.Ha=0;this.p=[];this.g={};this.d=this.Z=q;this.o=e;this.k=this.q=this.sa=q;this.ta=[];this.f=q;this.ea=La;Ca(this,d);if(this.c==w)this.r=[];this.Da=this.Ka=dd;this.sa=new R(this.o.T.l-this.Ka/2,this.o.T.i-this.Da/2);this.p=[];this.g={};this.g[y]=[];this.g[x]=[];this.g[z]=[];this.g[A]=[];this.g[B]=[];this.d=new ed;this.za=q;this.Ca=!0;if(d!==q)this.r.push(new Xa(this.c)),this.r.push(new Xa(this.c)),this.d.O=4;this.f=new Hb(this,this.c);
sa(this);switch(this.c){case w:this.Z=3;this.k=fd(E,0,this.o);break;case ea:this.Z=4;this.k=fd(E,v(2,5),this.o);break;case fa:this.Z=6;this.k=fd(E,v(5,10),this.o);break;case ga:this.Z=9;this.k=fd(E,v(10,15),this.o);break;default:throw new NotImplementedException("Planet type "+this.c+"not supported by planet constructor.");}this.zc=this.Z;e.R=this}var cd=1,dd=20;function Va(a){return a.zc+a.g[y].length}function gd(a){var b=0,e;for(e in a.g)e!=B&&(b+=a.g[e].length);return b}
function Yb(a){var b=gd(a),e;for(e in a.p){var d=a.p[e];d instanceof P&&d.c!=B&&b++}return b}function $b(a,b){var e=a.g[b].length,d;for(d in a.p){var g=a.p[d];g instanceof P&&g.c==b&&e++}return e}function pa(a,b,e,d,g){g.d.t-=b;b=e-hd(a.d,e);d-=id(a.d,d);if(b!=0||d!=0){var e=[],h;for(h in g.j)a.b!=g.j[h].b&&e.push(g.j[h]);e.sort((new pc(a)).W);for(h in e)if(b!=0&&(b-=hd(a.d,b)),d!=0&&(d-=id(a.d,d)),b==0&&d==0)break}}
function sa(a){Ya(a.f);if(a.q!==q){var b=1;a.ea==Pa?b=2:a.ea==Na&&(b=4);a.d.O+=Math.round(a.f.Ya/b);a.d.ub+=a.f.jc/b;a.d.C+=Math.round(a.f.xb/b);a.d.ia+=a.f.lc/b;a.d.A+=Math.round(a.f.vb/b);a.d.ha+=a.f.kc/b;a.d.Ba()}}
function Ua(a,b){b.Sc=!1;var e=[];if(a.p.length>0){var d=a.p.slice(0,1)[0],g=1;a.ea==Pa?g=4:a.ea==Na&&(g=8);g=Math.round(a.f.xa/g);d.eb+=g+a.Ha;a.Ha=0;if(d.eb>=d.Q){d=a.p.shift();d.zb=0;g="Nothing";a.p.length>0&&(g=a.p.slice(0,1)[0].ua());if(d instanceof P){a.g[d.c].push(d);if(d.c==B)a.k.F=!0;e.push(new M(jd,a,d.ua()+" built on planet: "+a.m+", next in queue: "+g))}else if(d instanceof J){var h=new Q(d.c);a.k.a[d.c].push(h);a.za=d.c;e.push(new M(kd,a,d.ua()+" built on planet: "+a.m+", next in queue: "+
g))}else if(d instanceof md&&a.g[d.pb].length>0){a.g[d.pb].pop();for(e.push(new M(nd,a,ha(d.pb)+" demolished on planet: "+a.m+", next in queue: "+g));Va(a)<a.r.length;)a.r.pop()}a.Ha=d.eb-d.Q;Ya(a.f)}else d.Mb(g)}else b.Sc=!0,d="",a.f.xa>0&&(d=", Gold generated"),e.push(new M(Dc,a,"Build queue empty on planet: "+a.m+d));return e}
function Ca(a,b){var e=0;if(a.q!==q){for(var d=a.p.length-1;d>=0;d--){var g=a,h=d,i=0;if(g.p.length>h){var f=[],j=m;for(j in g.p)f.push(g.p[j]);var l=f[h].cc();i+=l.Nb;g.q.d.da+=l.Nb;g.q.d.ia+=l.ic;g.q.d.ha+=l.dc;g.q.d.Ba();f.splice(h,1);g.p=[];for(j in f)g.p.push(f[j])}e+=i}a.g[B]=[];a.q.v[a.b]&&delete a.q.v[a.b];delete a.q.j[a.b]}a.q=b;if(a.q!==q){b.va[a.b]=a;if(aa(b.j)==0)b.Qa=a;b.j[a.b]=a}a.r.length==0&&a.r.push(new Xa(a.c));return e}
function Fa(a,b){var e=rc(a.k.a[E].length,a.k.a[F].length,a.k.a[G].length,a.k.a[H].length,a.k.a[I].length,a.o);od(e);e=new Jb(e,a.q);e.Ja=u.V.ka;b.B[a.b]=e}function ra(a,b){workers=miners=farmers=0;for(var e in a.r)switch(a.r[e].Y){case pd:farmers++;break;case qd:miners++;break;case rd:workers++}b.Xa=farmers;b.Ra=miners;b.ib=workers}
function hc(a,b,e,d,g,h,i){for(;g!==0;)if(g>0){if(e>0&&h<0)sd(a,qd).Y=pd,e--,b++,g--,h++;if(g!==0&&d>0&&i<0)sd(a,rd).Y=pd,d--,b++,g--,i++}else{if(h>0&&e<Va(a))sd(a,pd).Y=qd,b--,e++,g++,h--;if(g!==0&&i>0&&d<Va(a))sd(a,pd).Y=rd,b--,d++,g++,i--}for(;h!==0;)if(h>0){if(d>0&&i<0)sd(a,rd).Y=qd,d--,e++,h--,i++}else if(i>0&&d<Va(a))sd(a,qd).Y=rd,e--,d++,h++,i--;if(g!==0||h!==0||i!==0)throw Error("Couldn't move workers in Planet.UpdatePopulationWorkerTypesByDiff!");}
function td(a,b,e,d){var g=new qa;ra(a,g);for(var h=g.Xa,i=g.Ra,g=g.ib,f=b-h;h!=b;)if(f>0){if(i>0)sd(a,qd).Y=pd,i--,h++,f--;if(f>0&&g>0)sd(a,rd).Y=pd,g--,h++,f--}else{if(i<e&&i<Va(a))sd(a,pd).Y=qd,h--,i++,f++;if(f<0&&g<d&&g<Va(a))sd(a,pd).Y=rd,h--,g++,f++}for(f=e-i;i!=e;)if(f>0){if(g>0)sd(a,rd).Y=qd,g--,i++,f--}else if(g<d&&g<Va(a))sd(a,qd).Y=rd,i--,g++,f++;if(h!=b||i!=e||g!=d)throw Error("Couldn't move workers in Planet.UpdatePopulationWorkerTypes!");}
function sd(a,b){for(var e in a.r)if(a.r[e].Y==b)return a.r[e];throw Error("Couldn't find: "+b+" in Planet.getCitizenType!");}function Xb(a,b){var e=ba(b.r.length,a.r.length);e==0&&(e=ba(gd(b),gd(a)));return e}function fc(a,b){return ba(gc(b.f),gc(a.f))}function kc(a,b){this.Xc=a;this.Vc=b}kc.prototype.W=function(a,b){var e=0;return e=this.Xc>=this.Vc?ba(ic(b.f),ic(a.f)):ba(jc(b.f),jc(a.f))};
function pc(a){this.source=a;var b=this;this.W=function(a,d){var g=0,h=0,i=0;a!=b.source&&(h=mc(b.source.o,a.o),g=1);d!=b.source&&(i=mc(b.source.o,d.o),g=-1);g!==0&&(g=h==i?0:h<i?1:-1);return g}}function qc(a,b){this.source=a;this.yc=b;var e=this;this.W=function(a,b){var h=0,i=0,f=0;a!=e.source&&(i=mc(e.source.o,a.o),h=1);b!=e.source&&(f=mc(e.source.o,b.o),h=-1);h!==0&&(i=ud(e.yc,i,a),f=ud(e.yc,f,b),h=i==f?0:i<f?1:-1);return h}}
function ud(a,b,e){switch(e.c){case w:b+=3;break;case ea:b+=2;break;case fa:b+=1}a[e.b]&&(a=L(a[e.b].fa),a>=20&&a<40?b+=1:a>=40&&a<80?b+=2:a>=80&&(b+=3));return b}
function Hb(a,b){this.oa=this.pa=this.na=0;this.tb=2;this.Lc=this.xa=this.kc=this.vb=this.lc=this.xb=this.jc=this.Ya=0;this.h=a;switch(b){case w:this.na=0.5;this.oa=this.pa=2;break;case ea:this.na=1;this.pa=1.5;this.oa=0.5;break;case fa:this.na=1.5;this.oa=this.pa=0.75;break;case ga:this.na=2;this.pa=0.5;this.oa=0.25;break;default:throw new NotImplementedException("Planet type "+b+"not supported by PlanetPerTurnResourceGeneration constructor.");}Ya(this)}
function Ya(a){var b=new qa;ra(a.h,b);var e=a.na*b.Xa,d=a.pa*b.Ra,g=a.oa*b.Ra,b=a.tb*b.ib;a.Ya=Math.floor(e);a.xb=Math.floor(d);a.vb=Math.floor(g);a.xa=Math.floor(b);if(gd(a.h)>0){var h=a.h.g[z].length,i=a.h.g[A].length,f=a.h.g[x].length;if(h>0)h*=e*vd,a.Ya=Math.floor(e+h/1),a.jc=h%1;if(i>0)e=d*vd*i,a.xb=Math.floor(d+e/1),a.lc=e%1,d=g*vd*i,a.vb=Math.floor(g+d/1),a.kc=d%1;if(f>0)g=b*vd*f,a.xa=Math.floor(b+g/1),a.Lc=g%1}}var vd=0.5;function gc(a){return Math.round(a.na+a.na*vd*a.h.g[z].length)}
function ic(a){return Math.round(a.pa+a.pa*vd*a.h.g[A].length)}function jc(a){return Math.round(a.oa+a.oa*vd*a.h.g[A].length)}function ed(){this.ha=this.A=this.ia=this.C=this.ub=this.O=0}ed.prototype.Ba=function(){this.ub>=1&&(this.O+=Math.floor(this.ub/1),this.ub%=1);this.ia>=1&&(this.C+=Math.floor(this.ia/1),this.ia%=1);this.ha>=1&&(this.A+=Math.floor(this.ha/1),this.ha%=1)};function hd(a,b){if(a.C>=b)return a.C-=b,b;else{var e=b-a.C;a.C=0;return e}}
function id(a,b){if(a.A>=b)return a.A-=b,b;else{var e=b-a.A;a.A=0;return e}}function wd(a,b,e){this.Nb=a;this.ic=b;this.dc=e}function qa(){this.ib=this.Ra=this.Xa=m}
var xd=Class.extend({init:function(){this.zb=99;this.Q=this.eb=0;this.u=1;this.G=this.D=0},Mb:function(a){this.zb=a!==0?Math.ceil((this.Q-this.eb)/a):99},cc:function(){var a=1-this.eb/(this.Q*1);goldRefund=this.u*a;oreRefund=this.D*a;iridiumRefund=this.G*a;return new wd(goldRefund,oreRefund,iridiumRefund)}}),md=xd.extend({init:function(a){this._super();this.pb=a;this.u=0;this.Q=(new P(a)).Q/4},ua:function(){return"Demolish "+ha(this.pb)}}),P=xd.extend({init:function(a){this._super();this.c=a;switch(this.c){case y:this.Q=
16;this.D=2;this.G=1;this.u=3;break;case x:this.Q=32;this.D=4;this.G=2;this.u=6;break;case z:this.Q=4;this.u=1;break;case A:this.Q=8;this.D=1;this.u=2;break;case B:this.Q=90,this.D=8,this.G=4,this.u=12}},ua:function(){return ha(this.c)}}),J=xd.extend({init:function(a){this._super();this.c=a;switch(this.c){case I:this.Q=90;this.D=8;this.G=4;this.u=12;break;case H:this.Q=42;this.D=4;this.G=2;this.u=6;break;case G:this.Q=18;this.D=2;this.G=1;this.u=3;break;case F:this.Q=6;this.u=this.D=1;break;case E:this.Q=
2,this.u=1}},ua:function(){return ia(this.c)}}),x=1,y=2,z=3,A=4,B=5,w=0,ea=1,fa=2,ga=3,La=1,Pa=2,Na=3,pd=1,qd=2,rd=3;function Xa(a){this.cb=0;this.Y=pd;if(a==w)this.Y=qd};function Da(){this.a={};this.a[E]=[];this.a[F]=[];this.a[G]=[];this.a[H]=[];this.a[I]=[];this.F=!1;this.la=0;this.wb=this.hc=this.P=q;od(this);this.X=q}function od(a){a.F=!1;if(a.P!=q&&a.P.R!=q&&a.P.R.g[B].length>0)a.F=!0}Da.prototype.mb=function(a,b){yd(this,a,b,u.Ia)};function yd(a,b,e,d,g,h){a.X=new zd(a);d&&(mb.push(a.X),ib.addChild(a.X));a.F=!1;a.X.mb(b,e,g,h)}function tc(a){a.P=q;a.X.aa-=1;a.X.Dc();a.hc!=q&&a.hc(a)}function Ea(a,b,e){b.X.Aa=q;b.X.ca=q;b.X.aa=0;a.P=e;uc(a,b);od(a)}
function uc(a,b){a.a[E]=a.a[E].concat(b.a[E]);a.a[F]=a.a[F].concat(b.a[F]);a.a[G]=a.a[G].concat(b.a[G]);a.a[H]=a.a[H].concat(b.a[H]);a.a[I]=a.a[I].concat(b.a[I]);b.wb!=q&&b.wb(b)}function ya(a){var b=[],b=b.concat(a.a[I]),b=b.concat(a.a[H]),b=b.concat(a.a[G]),b=b.concat(a.a[F]);return b=b.concat(a.a[E])}function Ba(a,b){for(var e in a.a)for(var d=a.a[e],g=d.length-1;g>=0;g--)Aa(d[g])<=0&&d.splice(g,1);a.la+=b;if(a.la!=0&&a.F&&a.la>=64&&a.P!=q&&a.P.R!=q)a.P.R.g[B]=[],a.F=!1}
function L(a,b){if(b===q||typeof b=="undefined")b=!0;var e=0,d;for(d in a.a[E])e+=Aa(a.a[E][d]);for(d in a.a[F])e+=Aa(a.a[F][d]);for(d in a.a[G])e+=Aa(a.a[G][d]);for(d in a.a[H])e+=Aa(a.a[H][d]);for(d in a.a[I])e+=Aa(a.a[I][d]);b&&a.F&&(e+=64-a.la);return e}
function sc(a,b,e,d,g){var h=new Da;h.P=a.P;if(b>a.a[F].length||e>a.a[G].length||d>a.a[H].length||g>a.a[I].length)throw Error("Cannot send more ships than in the fleet!");for(var i=0;i<b;i++)h.a[F].push(a.a[F][0]),a.a[F].shift();for(i=0;i<e;i++)h.a[G].push(a.a[G][0]),a.a[G].shift();for(i=0;i<d;i++)h.a[H].push(a.a[H][0]),a.a[H].shift();for(i=0;i<g;i++)h.a[I].push(a.a[I][0]),a.a[I].shift();return h}function lc(a){var b=0;b+=a.a[F].length;b+=a.a[G].length;b+=a.a[H].length;b+=a.a[I].length;return b}
function Ha(a){var b=new Da;b.P=a.P;b.F=a.F;for(var e in a.a[E])b.a[E].push(Ad(a.a[E][e]));for(e in a.a[F])b.a[F].push(Ad(a.a[F][e]));for(e in a.a[G])b.a[G].push(Ad(a.a[G][e]));for(e in a.a[H])b.a[H].push(Ad(a.a[H][e]));for(e in a.a[I])b.a[I].push(Ad(a.a[I][e]));return b}
Da.prototype.ua=function(){var a="",b=-1,b=this.a[E].length;b>0&&(a=b+" Defender"+(b>1?"s":""));b=this.a[F].length;b>0&&(a!=""&&(a+=", "),a+=b+" Scout"+(b>1?"s":""));b=this.a[G].length;b>0&&(a!=""&&(a+=", "),a+=b+" Destroyer"+(b>1?"s":""));b=this.a[H].length;b>0&&(a!=""&&(a+=", "),a+=b+" Cruiser"+(b>1?"s":""));b=this.a[I].length;b>0&&(a!=""&&(a+=", "),a+=b+" Battleship"+(b>1?"s":""));this.F&&(a!=""&&(a+=", "),a+="1 Space Platform");a==""&&(a="No Ships");return a};
function Jb(a,b){this.Ja=0;this.fa=a;this.Ea=b}function Q(a){this.id=Bd++;this.c=a;this.qa=this.Na=0;switch(this.c){case E:this.Na=2;break;case F:this.Na=4;break;case G:this.Na=8;break;case H:this.Na=16;break;case I:this.Na=32}}var Bd=1;function Aa(a){return a.Na-a.qa}function Ad(a){var b=new Q(a.c);b.qa=a.qa;return b}function Cd(a,b,e){this.type=a;this.xc=b;this.vc=e;var d=this;this.W=function(a,b){var e=Dd(d,a),f=Dd(d,b);return e==f?0:e<f?-1:1}}
function Dd(a,b){var e=Aa(b);a.vc[b]&&(e-=a.vc[b]);e*=Ed(a.xc,a.type,!1,b.c)?1:Fd(a.xc,a.type,!1,b.c)?1E4:100;return e}function fd(a,b,e){var d=new Da;d.P=e;for(e=0;e<b;e++)d.a[a].push(new Q(a));return d}function rc(a,b,e,d,g,h){var i=new Da;i.P=h;for(h=0;h<a;h++)i.a[E].push(new Q(E));for(h=0;h<b;h++)i.a[F].push(new Q(F));for(h=0;h<e;h++)i.a[G].push(new Q(G));for(h=0;h<d;h++)i.a[H].push(new Q(H));for(h=0;h<g;h++)i.a[I].push(new Q(I));return i}var E=1,F=2,G=3,H=4,I=5;function M(a,b,e){this.c=a;this.h=b;this.gc=e;this.I=q}function vc(a,b){if(a.c>b.c)return-1;else if(a.c<b.c)return 1;return 0}var Ta=0,Wa=1,jd=2,kd=3,nd=4,Sa=5,Dc=6,Ka=7,Ja=8,Ga=9,Qa=10,Oa=11,Ra=12,Ia=13;function xa(a,b,e,d){this.Fc=a;this.ac=Ha(b);this.Ec=e;this.Zb=Ha(d);this.qb=q;this.Za=this.kb=0};function za(a,b,e,d,g,h,i){var f=[],f=f.concat(d);f.sort((new Cd(b,e,h)).W);for(d=0;d<a;d+=2){for(var j=f.length-1;j>=0;j--){var l=f[j],k={Starship:l,Damage:0};h[l.id]&&(k=h[l.id]);Aa(f[j])-k.Damage<=0&&f.splice(j,1)}g&&(b==H||f.length==0)?(l=2,Ed(e,b,!0,E)?l+=1:Fd(e,b,!0,E)&&(l-=1),l=v(0,l+1),i.enemyFleetSpacePlatformDamagePending+=l):f.length>0&&(j=f[0],l=2,Ed(e,b,!1,j.c)?l+=1:Fd(e,b,!1,j.c)&&(l-=1),l=v(0,l+1),l!=0&&(h[j.id]||(h[j.id]={Starship:j,Damage:0}),h[j.id].Damage+=l))}}
function Ed(a,b,e,d){if(a||e)if(a&&d==G)return!0;else{if(e&&b==H)return!0}else if(b==E&&d==I)return!0;else if(b==I&&d==H)return!0;else if(b==G&&d==F)return!0;else if(b==F&&d==E)return!0;return!1}function Fd(a,b,e,d){if(a||e)if(a&&d==H)return!0;else{if(e&&b==G)return!0}else if(b==I&&d==E)return!0;else if(b==H&&d==I)return!0;else if(b==F&&d==G)return!0;else if(b==E&&d==F)return!0;return!1};var Gd=jCanvas.DrawnObject.extend({init:function(a){this.h=a;this.sb=!1;this.Ua=q;this.Kb=this.Jb="yellow";this.Lb="";this.Db=new Uc(this.h.o.T.l+dd/2-2,this.h.o.T.i+dd/2-2,11,11);this.Bb=!1;this.Eb=Za;this.Fb=new Uc(this.h.o.T.l-dd/2-8,this.h.o.T.i+dd/2-2,11,11);this.Cb=!1;this.Gb=$a},draw:function(a){var b=this.h.Ka,e=this.h.Da,d=this.h.sa.l+b/2,g=this.h.sa.i+e/2;if(this.Ua){var h=new Image,i=this.h.sa.l-6,f=this.h.sa.i-7;this.h.c==w&&(i+=1);var j=this;h.onload=function(){a.drawImage(h,i,f);j.uc(a,
d,g)};h.src=this.Ua;if(this.Bb){var e=a.createImageData(this.Db.Ka,this.Db.Da),l;for(l in this.Eb)e.data[l]=this.Eb[l];a.putImageData(e,this.Db.l,this.Db.i)}if(this.Cb){e=a.createImageData(this.Fb.Ka,this.Fb.Da);for(l in this.Gb)e.data[l]=this.Gb[l];a.putImageData(e,this.Fb.l,this.Fb.i)}}else l=b*1.33,a.beginPath(),a.moveTo(d,g-e/2),a.bezierCurveTo(d-l/2,g-e/2,d-l/2,g+e/2,d,g+e/2),a.bezierCurveTo(d+l/2,g+e/2,d+l/2,g-e/2,d,g-e/2),a.lineWidth=2,a.strokeStyle="white",a.fillStyle="black",a.stroke(),a.fill(),
a.closePath(),this.uc(a,d,g)},uc:function(a,b,e){a.fillStyle=this.Jb;a.font="bolder 8pt Trebuchet MS,Tahoma,Verdana,Arial,sans-serif";a.textAlign="center";a.textBaseline="middle";a.fillText(this.h.o.b,b,e);a.fillStyle=this.Kb;a.font="bold 7pt Trebuchet MS,Tahoma,Verdana,Arial,sans-serif";a.fillText(this.Lb,b,e-14)},isInBounds:function(){return!1},pc:function(a){this.Ua=q;if(this.sb=Qc(a,this.h))switch(this.h.c){case ga:this.Ua="img/PlanetClass2.png";break;case fa:this.Ua="img/PlanetClass1.png";break;
case ea:this.Ua="img/PlanetDead.png";break;case w:this.Ua="img/PlanetAsteroid.png"}this.Cb=this.Bb=!1;var b=q;if(a.B[this.h.b])b=a.B[this.h.b].Ea;if(oc(a,this.h)){this.Jb=a.ba.toString();this.Kb=a.ba.toString();if(lc(this.h.k)>0)this.Bb=!0,this.Eb=a.Ib;if(this.h.g[B].length>0)this.Cb=!0,this.Gb=a.Hb;this.Lb=L(this.h.k)+""}else if(this.sb&&b!==q){this.Jb=b.ba.toString();this.Kb=b.ba.toString();if(lc(a.B[this.h.b].fa)>0)this.Bb=!0,this.Eb=b.Ib;if(a.B[this.h.b].fa.F)this.Cb=!0,this.Gb=b.Hb;this.Lb=L(a.B[this.h.b].fa)+
""}else this.Jb=this.sb&&this.h.c==ea?"black":"yellow",this.Kb="yellow",this.Lb=this.sb&&this.h.b in a.B?L(a.B[this.h.b].fa)+"":""}});var zd=jCanvas.DrawnObject.extend({init:function(a){this.fa=a;this.fa.X=this;this.Aa=this.ca=q;this.yb=new Uc;this.oc="ETA";this.Ma=new R;this.aa=this.La=0;this.hb=new Uc;this.hb.Da=10;this.hb.Ka=10;this.ma=new Vc},draw:function(a){if(this.La>0){a.strokeStyle="green";a.lineWidth=1.5;a.beginPath();a.moveTo(this.ma.qc,this.ma.rc);a.lineTo(this.ma.Ab,this.ma.Yb);a.closePath();a.stroke();var b=new Image,e=this.hb.l,d=this.hb.i;b.onload=function(){a.drawImage(b,e,d)};b.src="img/starship.png";a.fillStyle=
"green";a.font="bold 8px sans-serif";a.textAlign="left";a.textBaseline="alphabetic";a.fillText(this.oc,this.yb.l,this.yb.i)}},isInBounds:function(){return!1},mb:function(a,b,e,d){this.Aa=a;this.ca=b;this.fa.ca=this.ca;this.La=d;if(!this.La)this.La=mc(this.Aa,this.ca);this.aa=this.La;if(e)this.aa=e;this.Dc()},Dc:function(){if(this.aa!=0){this.ma.Ab=this.ca.T.l;this.ma.Yb=this.ca.T.i;var a=(this.La-this.aa)*1/(this.La*1);this.Ma.l=this.Aa.T.l-(this.Aa.T.l-this.ma.Ab)*a;this.Ma.i=this.Aa.T.i-(this.Aa.T.i-
this.ma.Yb)*a;this.ma.qc=this.Ma.l;this.ma.rc=this.Ma.i;this.oc=this.aa+(this.aa>1?" Turns":" Turn");a=8;this.ma.Ab>this.Aa.T.l&&(a=this.aa>9?-40:this.aa==1?-30:-35);this.yb.l=this.Ma.l+a;this.yb.i=this.Ma.i+4;this.hb.l=this.Ma.l-5;this.hb.i=this.Ma.i-5}else this.La=0;if(this.layer)this.layer.needsDisplay=!0}});function Pb(a,b,e,d,g,h){this.bc=!1;this.Ac=g;this.tc=h;var i=this;this.rb=$(a).dialog({autoOpen:!1,resizable:!1,title:b,width:e,height:d,modal:!0,buttons:[{text:"Ok",click:function(){i.bc=!0;typeof i.Ac=="function"&&i.Ac();i.rb.dialog("close")}},{text:"Cancel",click:function(){i.bc=!1;typeof i.tc=="function"&&i.tc();i.rb.dialog("close")}}]})}Pb.prototype.open=function(){this.rb.dialog("open")};function xc(a,b){a.rb.dialog("option","title",b)};var yc=[];function Kb(){db.BeginGame();qb.clear();for(var a in u.U){var b=new Gd(u.U[a]);lb[u.U[a].b]=b;hb.addChild(b)}Bc();Nc(u.J,u.H.Qa.o);Ac();zc()}function Ec(){var a=yc.length-1;if(a>=0){var b=yc[a];yc.splice(a,1);u.H.wa.nb&&Hd(b)}}function Id(){u.Ia=!0;Bc();Ac();$("#MainMenuButtonGameOver").show()}
var Cc=JSListBox.Item.extend({init:function(a){this.value=a.gc;this.L=q;this.ra=a},render:function(){return'<a href="#" style="color:'+this.L+'">'+this.value+"</a>"},onClick:function(){this.ra!=q&&this.ra.h!=q&&(Nc(u.J,this.ra.h.o),Ac())},onDblClick:function(){this.ra&&(this.ra.c==Ja||this.ra.c==Ka||this.ra.c==Ga||this.ra.c==Ia)&&Hd(this.ra)}});var Jd=q,T=q,Kd=0,Ld=0,Md=0,Nd=0,Od=0,Pd=0,Qd=0,Rd=0,Sd=0,Td=0,Ud=0,U=[],V=q,Vd=0,Wd=q,Xd=q,Yd=!1,Zd=q,W=q,$d=q,ae=q,be=q,ce=q,de=q,ee=q,fe=q,ge=q,he=q,ie=q,X=[];
function Mb(){$("#ButtonDemolishFarm, #ButtonDemolishMine, #ButtonDemolishFactory, #ButtonDemolishColony").button({icons:{primary:"icon_demolish"},text:!1});$("#SliderFarmers").slider({value:0,step:1,min:0,max:10,slide:je});$("#SliderMiners").slider({value:0,step:1,min:0,max:10,slide:ke});$("#SliderWorkers").slider({value:0,step:1,min:0,max:10,slide:le});$("#ButtonBuildQueueAddSelectedItem").button({icons:{primary:"icon_build_queue_add"},text:!1});$("#ButtonBuildQueueRemoveSelectedItem").button({icons:{primary:"icon_build_queue_remove"},
text:!1});$("#ButtonBuildQueueMoveSelectedItemDown").button({icons:{primary:"icon_build_queue_down"},text:!1});$("#ButtonBuildQueueMoveSelectedItemUp").button({icons:{primary:"icon_build_queue_up"},text:!1});$("#ButtonBuildQueueAddSelectedItem").click(function(){me()});$("#ButtonBuildQueueRemoveSelectedItem").click(function(){var a=W.SelectedItem,b=W.SelectedIndex;a!=q&&b!=q&&(a=a.ya.cc(),V.da+=a.Nb,V.ia+=a.ic,V.ha+=a.dc,V.Ba(),U.splice(b,1),W.removeAt(b),ne(),oe(),pe(),qe())});$("#ButtonBuildQueueMoveSelectedItemDown").click(function(){re(!1)});
$("#ButtonBuildQueueMoveSelectedItemUp").click(function(){re(!0)});$("#ButtonDemolishFarm").click(function(){se(z)});$("#ButtonDemolishMine").click(function(){se(A)});$("#ButtonDemolishFactory").click(function(){se(x)});$("#ButtonDemolishColony").click(function(){se(y)});$("#BuildLastShipCheckBoxLabel").attr("title","If this option is checked and the build queue is empty at the end of the turn,\r\nthe ship last built on this planet will be added to the queue.\r\nIn order to build the ship, sufficient resources must exist\r\nas well as a surplus of gold to cover the amount of food shipped last turn.");
$("#BuildLastShipCheckBox").attr("checked",!0);Zd=new JSListBox({containerSelector:"ItemsAvailableListBox"});W=new JSListBox({containerSelector:"BuildQueueListBox"});$d=new te(z);ae=new te(A);be=new te(y);ce=new te(x);de=new te(B);ee=new ue(E);fe=new ue(F);ge=new ue(G);he=new ue(H);ie=new ue(I);X.push($d);X.push(ae);X.push(be);X.push(ce);X.push(de);X.push(ee);X.push(fe);X.push(ge);X.push(he);X.push(ie);Jd=new Pb("#planetViewDialog","Planet View",568,485,ve,we);Xd=Wd=xe}
function Vb(a){T=a;var b="";switch(a.c){case ga:b="img/PlanetClass2.png";break;case fa:b="img/PlanetClass1.png";break;case ea:b="img/PlanetDead.png";break;case w:b="img/PlanetAsteroid.png"}$("#PlanetImage").css("background-image","url("+b+")");$("#TextBlockPlanetType").text(da(a.c));Rd=a.g[z].length;Sd=a.g[A].length;Td=a.g[x].length;Ud=a.g[y].length;$("#PlanetViewFarmCount").text(Rd);$("#PlanetViewMineCount").text(Sd);$("#PlanetViewFactoryCount").text(Td);$("#PlanetViewColonyCount").text(Ud);$("#PlanetViewSpacePlatformCount").text(a.g[B].length);
ye();b="";b+="Base Worker Resource Generation Per Turn:\r\n";b+="Food: "+T.f.na+"\r\n";b+="Ore: "+T.f.pa+"\r\n";b+="Iridium: "+T.f.oa+"\r\n";b+="Production: "+T.f.tb+"\r\n\r\n";b+="Worker Resource Generation with Improvements:\r\n";b+="Food: "+(T.f.na+T.f.na*vd*T.f.h.g[z].length)+"\r\n";b+="Ore: "+(T.f.pa+T.f.pa*vd*T.f.h.g[A].length)+"\r\n";b+="Iridium: "+(T.f.oa+T.f.oa*vd*T.f.h.g[A].length)+"\r\n";b+="Production: "+(T.f.tb+T.f.tb*vd*T.f.h.g[x].length)+"\r\n\r\n";b+="Food amount on planet: "+T.d.O+
"\r\n";$("#PlanetImage").attr("title","Planet Stats:\r\n"+b);Kd=a.r.length;$("#SliderFarmers").slider("option","max",Kd);$("#SliderMiners").slider("option","max",Kd);$("#SliderWorkers").slider("option","max",Kd);b=new qa;ra(a,b);Ld=b.Xa;Md=b.Ra;Nd=b.ib;Od=Ld;Pd=Md;Qd=Nd;$("#SliderFarmers").slider("value",Ld);$("#TextBoxFarmers").text(Ld+"");$("#SliderMiners").slider("value",Md);$("#TextBoxMiners").text(Md+"");$("#SliderWorkers").slider("value",Nd);$("#TextBoxWorkers").text(Nd+"");U=[];for(var e in a.p)U.push(a.p[e]);
V=new ze(a.q);Vd=a.Ha;Zd.setSelectedItem(q);ne();Ae();pe();$("#ButtonBuildQueueAddSelectedItem").button("disable");$("#ButtonBuildQueueRemoveSelectedItem").button("disable");$("#ButtonBuildQueueMoveSelectedItemDown").button("disable");$("#ButtonBuildQueueMoveSelectedItemUp").button("disable");oe();T.Ca?$("#BuildLastShipCheckBox").prop("checked",!0):$("#BuildLastShipCheckBox").prop("checked",!1);$("#BuildLastShipCheckBoxLabel").text("Build Last Ship");$("#LastShipBuiltTextBlock").text("");T.za!=q&&
$("#LastShipBuiltTextBlock").text("Last Built: "+ia(T.za));xc(Jd,"Planet "+a.m+" View");Jd.open()}
function qe(){$("#ButtonBuildQueueRemoveSelectedItem").button("disable");$("#ButtonBuildQueueMoveSelectedItemDown").button("disable");$("#ButtonBuildQueueMoveSelectedItemUp").button("disable");W.SelectedItem!=q&&($("#ButtonBuildQueueRemoveSelectedItem").button("enable"),W.SelectedIndex!=W.items.length-1&&$("#ButtonBuildQueueMoveSelectedItemDown").button("enable"),W.SelectedIndex!=0&&$("#ButtonBuildQueueMoveSelectedItemUp").button("enable"))}
function Be(){Zd.SelectedItem!=q&&Zd.SelectedItem.enabled?$("#ButtonBuildQueueAddSelectedItem").button("enable"):$("#ButtonBuildQueueAddSelectedItem").button("disable")}function ye(){$("#TextBlockFoodPerTurn").text(T.f.Ya);$("#TextBlockOrePerTurn").text(T.f.xb);$("#TextBlockIridiumPerTurn").text(T.f.vb);$("#TextBlockProductionPerTurn").text(T.f.xa)}
function ne(){var a=gd(T),b;for(b in U){var e=U[b];e instanceof P&&e.c!=B&&a++}T.Z-a<=0?($d.z=!1,ae.z=!1,be.z=!1,ce.z=!1):($d.z=!0,ae.z=!0,be.z=!0,ce.z=!0);de.z=T.g[x].length==0?!1:!0;if(!(a=T.g[B].length>0))a:{for(var d in U)if(a=U[d],a instanceof P&&a.c==B){a=!0;break a}a=!1}if(a)de.z=!1;ge.z=T.g[x].length==0?!1:!0;T.g[B].length==0?(he.z=!1,ie.z=!1):(he.z=!0,ie.z=!0);for(var g in X)if(d=X[g],d instanceof te){if(d.z)d.Wa=V.t<d.M.u||V.A<d.M.G||V.C<d.M.D?!1:!0}else if(d instanceof ue&&d.z)d.Wa=V.t<
d.N.u||V.A<d.N.G||V.C<d.N.D?!1:!0;if(Zd.SelectedItem!=q&&(!Zd.SelectedItem.z||!Zd.SelectedItem.Wa))Zd.setSelectedItem(q),Zd.refresh();Zd.clear();Zd.addItems(X)}function Ae(){W.clear();var a=Vd,b;for(b in U){var e=U[b];e.Mb(T.f.xa+a);a=0;e=new Ce(e);W.addItem(e)}}
function pe(){Rd-De(z)>0?$("#ButtonDemolishFarm").css({visibility:"visible"}):$("#ButtonDemolishFarm").css({visibility:"hidden"});Sd-De(A)>0?$("#ButtonDemolishMine").css({visibility:"visible"}):$("#ButtonDemolishMine").css({visibility:"hidden"});Td-De(x)>0?$("#ButtonDemolishFactory").css({visibility:"visible"}):$("#ButtonDemolishFactory").css({visibility:"hidden"});Ud-De(y)>0?$("#ButtonDemolishColony").css({visibility:"visible"}):$("#ButtonDemolishColony").css({visibility:"hidden"})}
function oe(){$("#TextBlockCurrentGoldAmount").text(V.t);$("#TextBlockCurrentOreAmount").text(V.C);$("#TextBlockCurrentIridiumAmount").text(V.A)}function De(a){var b=0,e;for(e in U){var d=U[e];d instanceof md&&d.pb==a&&b++}return b}function se(a){a=new md(a);U.push(a);pe();Ae()}
function Ee(a,b){var e=0;Yd=!0;Wd!=a&&(Xd=xe);var d=$("#SliderFarmers").slider("value"),g=$("#SliderMiners").slider("value"),h=$("#SliderWorkers").slider("value");switch(a){case Y:d=b;e=d-Ld;break;case Z:g=b;e=g-Md;break;case Fe:h=b,e=h-Nd}var i=!1,f=!1,j=!1;if(e>0)i=Ld!=0,f=Md!=0,j=Nd!=0;else if(e<0)i=Ld!=Kd,f=Md!=Kd,j=Nd!=Kd;else{Yd=!1;return}for(;e!=0;){var l=1;e<0&&(l=-1);var k=xe;switch(a){case Y:k=f&&!j?Z:!f&&j?Fe:g==h?Xd!=Z?Z:Fe:e>0?g>h?Z:Fe:g<h?Z:Fe;break;case Z:k=i&&!j?Y:!i&&j?Fe:d==h?Xd!=
Y?Y:Fe:e>0?d>h?Y:Fe:d<h?Y:Fe;break;case Fe:k=i&&!f?Y:!i&&f?Z:d==g?Xd!=Y?Y:Z:e>0?d>g?Y:Z:d<g?Y:Z}switch(k){case Y:d-=l;$("#SliderFarmers").slider("value",d);Xd=Y;break;case Z:g-=l;$("#SliderMiners").slider("value",g);Xd=Z;break;case Fe:h-=l;$("#SliderWorkers").slider("value",h);Xd=Fe;break;default:throw Error("Unable to determine slider to change in PlanetViewControl!");}Ld=d;Md=g;Nd=h;e>0?e--:e<0&&e++}Yd=!1;Wd=a;$("#TextBoxFarmers").text(Ld);$("#TextBoxMiners").text(Md);$("#TextBoxWorkers").text(Nd);
td(T,Ld,Md,Nd);Ya(T.f);var e=Vd,n;for(n in W.items)W.items[n].ya.Mb(T.f.xa+e),e=0;W.refresh();ye()}function je(a,b){Yd||Ee(Y,b.value)}function ke(a,b){Yd||Ee(Z,b.value)}function le(a,b){Yd||Ee(Fe,b.value)}function re(a){var b=W.SelectedIndex;if(!(b==0&&a)&&(b!=W.items.length-1||a)){var e=W.items[b];W.items.splice(b,1);U.splice(b,1);a?(W.items.splice(b-1,0,e),U.splice(b-1,0,e.ya),W.setSelectedIndex(b-1)):(W.items.splice(b+1,0,e),U.splice(b+1,0,e.ya),W.setSelectedIndex(b+1));qe();W.refresh()}}
function me(){var a=Zd.SelectedItem;a!=q&&(a instanceof te?a.z&&(V.t>=a.M.u&&V.A>=a.M.G&&V.C>=a.M.D?(V.t-=a.M.u,V.A-=a.M.G,V.C-=a.M.D,a=new P(a.M.c),U.push(a)):new wc("Insufficient resources","Insufficient resources: (Gold/Ore/Iridium)\r\nRequires  ("+a.M.u+" / "+a.M.D+" / "+a.M.G+")\r\nYou have ("+V.t+" / "+V.C+" / "+V.A+")")):a instanceof ue&&a.z&&(V.t>=a.N.u&&V.A>=a.N.G&&V.C>=a.N.D?(V.t-=a.N.u,V.A-=a.N.G,V.C-=a.N.D,a=new J(a.N.c),U.push(a)):new wc("Insufficient resources","Insufficient resources: (Gold/Ore/Iridium)\r\nRequires  ("+
a.N.u+" / "+a.N.D+" / "+a.N.G+")\r\nYou have ("+V.t+" / "+V.C+" / "+V.A+")")),ne(),Ae(),oe())}function ve(){td(T,Ld,Md,Nd);Ya(T.f);T.p=[];for(var a in U)T.p.push(U[a]);a=new ze(T.q);pa(T,a.t-V.t,a.C-V.C,a.A-V.A,T.q);T.q.d.da=V.da;T.q.d.ia=V.ia;T.q.d.ha=V.ha;T.q.d.Ba();T.Ca=!0;if(!$("#BuildLastShipCheckBox").attr("checked"))T.Ca=!1;Ac();zc()}function we(){td(T,Od,Pd,Qd);Ya(T.f)}
var Ce=JSListBox.Item.extend({ya:q,init:function(a){this.ya=a},render:function(){var a=this.ya.ua(),b="",b=" ("+this.ya.zb+")";a+=" "+this.ya.eb+"/"+this.ya.Q+b;return'<a href="#">'+a+"</a>"},onClick:function(){qe()}}),te=JSListBox.Item.extend({ob:"",M:q,z:!0,Wa:!0,L:"white",init:function(a){var b="";switch(a){case z:b="Farms increase amount of Food produced by each farmer.";break;case A:b="Mines increase the amount of Ore and Iridium produced by each miner.";break;case x:b="Factories increase the production generated by each worker.\r\nAllows construction of Space Platforms and Destroyers.";
break;case y:b="Colonies increase the planet's maximum population by one.";break;case B:b="Space Platforms provide planetary defense.\r\nAllows construction of Cruisers and Battleships.\r\nAdvantage against: Destroyers, Disadvantage Against: Cruisers"}this.ob=b;this.M=new P(a)},render:function(){this.enabled=!1;if(this.z)if(this.Wa){if(this.z)this.L="white",this.enabled=!0}else this.L="yellow";else this.L="darkgray";var a=ha(this.M.c);a+=" ("+this.M.u+" / "+this.M.D+" / "+this.M.G+")";return this.enabled?
'<a href="#" title="'+this.ob+'" style="color:'+this.L+'">'+a+"</a>":'<a style="color:'+this.L+'">'+a+"</a>"},onClick:function(){Be()},onDblClick:function(){me()}}),ue=JSListBox.Item.extend({ob:"",N:q,z:!0,Wa:!0,L:"white",init:function(a){var b="";switch(a){case E:b="Defenders protect a planet from attacking fleets but cannot move between planets.\r\nAdvantage against: Destroyers, Disadvantage Against: Scouts";break;case F:b="Scouts are the weakest ship equipped with warp drive.\r\nAdvantage against: Defenders, Disadvantage Against: Space Platforms";
break;case G:b="Destroyers require a Factory in order to build and are twice the strength of a Scout.\r\nAdvantage against: Battleships, Disadvantage Against: Defenders";break;case H:b="Cruisers require a Space Platform in order to build and are twice the strength of a Destroyer.\r\nAdvantage against: Space Platforms, Disadvantage Against: Battleships";break;case I:b="Battleships require a Space Platform in order to build and are twice the strength of a Cruiser.\r\nAdvantage against: Cruisers, Disadvantage Against: Destroyers"}this.ob=
b;this.N=new J(a)},render:function(){this.enabled=!1;if(this.z)if(this.Wa){if(this.z)this.L="white",this.enabled=!0}else this.L="yellow";else this.L="darkgray";var a=ia(this.N.c);a+=" ("+this.N.u+" / "+this.N.D+" / "+this.N.G+")";return this.enabled?'<a href="#" title="'+this.ob+'" style="color:'+this.L+'">'+a+"</a>":'<a style="color:'+this.L+'">'+a+"</a>"},onClick:function(){Be()},onDblClick:function(){me()}}),xe=0,Y=1,Z=2,Fe=3;
function ze(a){this.t=a.d.t;this.da=0;this.C=na(a);this.ia=0;this.A=oa(a);this.ha=0}ze.prototype.Ba=function(){this.da>=1&&(this.t+=Math.floor(this.da/1),this.da%=1);this.ia>=1&&(this.C+=Math.floor(this.ia/1),this.ia%=1);this.ha>=1&&(this.A+=Math.floor(this.ha/1),this.ha%=1)};var Pc=q,Mc=q,Oc=q,Lc=q;
function Nb(){$("#SliderScouts").slider({value:0,step:1,min:0,max:10,change:Ge});$("#SliderDestroyers").slider({value:0,step:1,min:0,max:10,change:He});$("#SliderCruisers").slider({value:0,step:1,min:0,max:10,change:Ie});$("#SliderBattleships").slider({value:0,step:1,min:0,max:10,change:Je});$("#ButtonSendNoShips, #ButtonSendAllShips").button();$("#ButtonSendNoShips").click(function(){$("#SliderScouts").slider("value",0);$("#SliderDestroyers").slider("value",0);$("#SliderCruisers").slider("value",0);
$("#SliderBattleships").slider("value",0)});$("#ButtonSendAllShips").click(function(){$("#SliderScouts").slider("value",$("#SliderScouts").slider("option","max"));$("#SliderDestroyers").slider("value",$("#SliderDestroyers").slider("option","max"));$("#SliderCruisers").slider("value",$("#SliderCruisers").slider("option","max"));$("#SliderBattleships").slider("value",$("#SliderBattleships").slider("option","max"))});Pc=new Pb("#sendShipsDialog","Send Ships",380,330,Ke,Le)}
function Je(a,b){$("#TextBoxBattleships").text(b.value)}function Ie(a,b){$("#TextBoxCruisers").text(b.value)}function He(a,b){$("#TextBoxDestroyers").text(b.value)}function Ge(a,b){$("#TextBoxScouts").text(b.value)}function Ke(){var a=Mc.k,b=parseInt($("#TextBoxScouts").text()),e=parseInt($("#TextBoxDestroyers").text()),d=parseInt($("#TextBoxCruisers").text()),g=parseInt($("#TextBoxBattleships").text());b!=0||e!=0||d!=0||g!=0?(Lc=sc(a,b,e,d,g),yd(Lc,Mc.o,Oc.o,!0),Mc.ta.push(Lc)):Lc=q;Kc(!0)}
function Le(){Kc(!1)};var Ob=q;
function Hd(a){var b="";b+=a.gc+"<br />";var e="";if(a.c==Ga||a.c==Ia)if(e="No Resources Looted.",a.h.d.O!=0||a.I.Za!=0||a.h.d.C!=0||a.h.d.A!=0)e="",e+=a.h.d.O!=0?a.h.d.O+" Food":"",e+=a.I.Za!=0?(e?", ":"")+a.I.Za+" Gold":"",e+=a.h.d.C!=0?(e?", ":"")+a.h.d.C+" Ore":"",e+=a.h.d.A!=0?(e?", ":"")+a.h.d.A+" Iridium":"",e="Resources looted: "+e;b+=e+"<br />";b+="Attacking Fleet (strength "+L(a.I.Zb)+", Chance to Win: "+a.I.kb+"%): <br />";b+=a.I.Zb.ua()+"<br /><br />";b+="Defending Fleet (strength "+L(a.I.ac)+
"): <br />";b+=a.I.ac.ua()+"<br /><br />";b+="Ships Remaining: <br />";b+=a.I.qb.ua()+"<br />";u.H.wa.nb?$("#NeverShowPlanetaryConflictPopupsCheckbox").prop("checked",!1):$("#NeverShowPlanetaryConflictPopupsCheckbox").prop("checked",!0);$("#PlanetaryConflictSummary").html(b);xc(Ob,a.I.Ec.m+" Attacked "+ca(a.h,a.I.Fc)+" at Planet: "+a.h.m);Ob.open()}function Qb(){u.H.wa.nb=!0;if($("#NeverShowPlanetaryConflictPopupsCheckbox").attr("checked"))u.H.wa.nb=!1;setTimeout(function(){Ec()},100)}
function Rb(){setTimeout(function(){Ec()},100)};var Sb=q;function Tb(){Id()}function Ub(){Id()};function wc(a,b){$("#AstriarchAlertBox").html(b);this.rb=$("#AstriarchAlertBox").dialog({autoOpen:!0,title:a,width:200,height:100,modal:!0})};function Bb(){var a=!1;localStorage&&localStorage.getItem("astriarch_save")!=q&&(a=!0);return a}function Ib(a,b,e){var d=new Lb(b.c,b.m);d.b=b.b;d.d=jQuery.extend(d.d,b.d);b.ba=jQuery.extend(new bb(0,0,0,0),b.ba);d.c==ma?d.ba=b.ba:Yc(d,b.ba);d.Fa=b.Fa;d.wa=b.wa;for(var g in b.Sb)Ca(e[b.Sb[g]],d);for(g in b.Ob){var h=b.Ob[g];d.va[h]=e[h]}for(g in b.v)h=Fb(b.v[g]),d.v[g]=h;d.Qa=e[b.Ic];for(g in b.Vb)d.ga.push(Gb(b.Vb[g],a));return d}
function Fb(a){var b=q;a.ab==Me?b=new P(a.c):a.ab==Ne?b=new J(a.c):a.ab==Oe&&(b=new md(a.c));return jQuery.extend(b,a)}
function Gb(a,b){var e=new Da;e.F=a.F;e.la=a.la;for(var d in a.a[E]){var g=jQuery.extend(new Q(E),a.a[E][d]);e.a[E].push(g)}for(d in a.a[F])g=jQuery.extend(new Q(F),a.a[F][d]),e.a[F].push(g);for(d in a.a[G])g=jQuery.extend(new Q(G),a.a[G][d]),e.a[G].push(g);for(d in a.a[H])g=jQuery.extend(new Q(H),a.a[H][d]),e.a[H].push(g);for(d in a.a[I])g=jQuery.extend(new Q(I),a.a[I][d]),e.a[I].push(g);e.P=q;if(a.Qb)e.P=Eb(b.J,a.Qb);a.Cc&&(d=Eb(b.J,a.Cc),g=Eb(b.J,a.Hc),yd(e,d,g,a.Rc,a.aa,mc(d,g)));return e}
function Wb(a){this.Ia=a.Ia;this.Sa=a.Sa;this.bb=a.bb;this.V=a.V;var b=[],e={},d;for(d in a.S)e[a.S[d].b]=!0;this.lb=[];for(d in a.S)this.lb.push(new Pe(a.S[d],e,b));this.Xb=[];for(d in b)this.Xb.push(new Pe(b[d],e,b));this.Wb=[];for(d in a.U)this.Wb.push(new Qe(a.U[d]));this.Version="1.2.1"}
function Pe(a,b,e){this.b=a.b;this.c=a.c;this.m=a.m;this.d=a.d;this.ba=a.ba;this.Fa=a.Fa;this.wa=a.wa;this.Sb=[];for(var d in a.j)this.Sb.push(a.j[d].b);this.Ob=[];for(d in a.va)this.Ob.push(a.va[d].b);this.Pb={};for(d in a.B)this.Pb[d]=new Re(a.B[d],b,e);this.v=a.v;for(d in this.v)Se(this.v[d]);this.Ic=a.Qa.b;this.Vb=[];for(d in a.ga)this.Vb.push(new Te(a.ga[d],this.c==ma))}
function Te(a,b){this.a=a.a;this.F=a.F;this.la=a.la;this.Qb=q;if(a.P)this.Qb=a.P.T;if(a.X)this.Cc=a.X.Aa.T,this.Hc=a.X.ca.T,this.aa=a.X.aa,this.Rc=b}function Re(a,b,e){this.Ja=a.Ja;this.Nc=new Te(a.fa,!1);if(a.Ea)a.Ea.b in b||(e.push(a.Ea),b[a.Ea.b]=!0),this.ec=a.Ea.b}
function Qe(a){this.b=a.b;this.m=a.m;this.c=a.c;this.r=a.r;this.Ha=a.Ha;this.p=a.p;for(var b in this.p)Se(this.p[b]);this.g=a.g;this.Z=a.Z;this.d=a.d;this.sa=a.sa;this.Kc=new Te(a.k,!1);this.Rb=[];for(b in a.ta)this.Rb.push(new Te(a.ta[b],a.q.c==ma));this.ea=a.ea;this.g=a.g;this.za=a.za;this.Ca=a.Ca}var Me=1,Ne=2,Oe=3;function Se(a){a.ab=0;if(a instanceof P)a.ab=Me;else if(a instanceof J)a.ab=Ne;else if(a instanceof md)a.ab=Oe};
